### ISSUE TITLE
Trim too long lines

### ISSUE THREAD

**Issue by crassirostris** [GoogleCloudPlatform/fluent-plugin-google-cloud#102]
Stackdriver currently [has](https://cloud.google.com/logging/quota-policy) a 100KB limit on the size of the log entry.

Sometimes keeping a trimmed version of the message is better than dropping it, even without the rest of the message (as described in https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/79).

Therefore it would be great to have an option (e.g. 'max_log_size') that would allow to trim messages that contain more bytes than this value.

This can be also a separate plugin just for the purpose of trimming, but then it would be great to have a reference in the documentation here.

CC @piosz @igorpeshansky

**Comment by ilyaskorik** [comment]
Any news?

**Comment by jkohen** [comment]
@qingling128 can you please triage this issue?

**Comment by qingling128** [comment]
Trimming can be done with something like below. We are doing this for GKE.

```
    <filter **>
      @type record_transformer
      enable_ruby true
      <record>
        message ${record['message'].length > 100000 ? "[Trimmed]#{record['message'][0..100000]}..." : record['message']}
      </record>
    </filter>
111
