### ISSUE TITLE
Feature Request: textPayload

### ISSUE THREAD

**Issue by evmin** [GoogleCloudPlatform/fluent-plugin-google-cloud#113]
As a system administrator I would like to improve the readability of the log entries in Google Logging. With the label map configuration I can direct all meta data into labels, leaving only a single field - the message - to display.

I would like to be able to:
- Configure the field name to be used as the text output
- Deliver the field as textPayload instead of jsonPayload

**Comment by mr-salty** [comment]
If the only remaining field is "message", the plugin will use textPayload.

The field name should be configurable - there is an old issue open for that: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/4

**Comment by evmin** [comment]
Brilliant idea.

Though it is not what I am observing:
<img width="1068" alt="screen shot 2017-01-19 at 8 46 29 am" src="https://cloud.githubusercontent.com/assets/5507517/22084379/0df1278a-de24-11e6-89f3-46f2bced8633.png">

I suspect it might be due to the fact that there are in fact three fields remaining when the event reaches the plugin:

```
{
  "CONTAINER_NAME": "smart",    
  "CONTAINER_ID": "13eda614bfa0",
  "MESSAGE": "Message History"
}
```

However two of them are mapped to labels:
```
    label_map {
         "CONTAINER_NAME": "CONTAINER_NAME",
         "CONTAINER_TAG": "CONTAINER_TAG"
     }
````    

So, even though essentially the `MESSAGE` field is the only one, it is still uploaded as jsonPayload.

And I would like to be able to upload it as a textPayload.

**Comment by igorpeshansky** [comment]
I believe Todd means "message" -- it's case sensitive.

**Comment by evmin** [comment]
Thank you - it works.

This is fantastic. Would be great if could have been made a little less arcane - explicit parameter, docs, etc..

Once again - thank you! As far as I am concerned - the issue is solved.

**Comment by jkohen** [comment]
I'm glad the issue was solved. Closing now.
