### ISSUE TITLE
format json doesn't work

### ISSUE THREAD

**Issue by kdabir** [GoogleCloudPlatform/fluent-plugin-google-cloud#124]
My application generates a log file which is formatted as per fluentd json format config (One Json object per line)

This works when I set `format` to `none` but entire json is sent in `textPayload`. When I set `format` as `json`, The logs are not even forwarded to Google Stackdriver Logging (at least i can't see them in the UI).

```
<source>
  @type tail
  format json
  path /var/log/my-app/json-formatted.log
  pos_file /var/lib/google-fluentd/pos/my-app-json-formatted-log.pos
  read_from_head true
  tag xxxxx
</source>
```

There is no error/warning in `/var/log/google-fluentd/google-fluentd.log`.

I could find similar question asked on StackOverflow [here](http://stackoverflow.com/questions/41034377/format-json-not-working-in-google-fluend) but the suggested solution also didn't work for me.

**Comment by qingling128** [comment]
Hi @kdabir, mind providing some sample logs that did not work for you?

**Comment by qingling128** [comment]
Also which version of the plugin are you using?

**Comment by kdabir** [comment]
Excerpt from Log file...

```
{"ca":"2","guid":"23430ec0-9066-11e6-8cd3-3f324f56f302","requestid":"23430ec0-9066-11e6-8cd3-3f324f56f302|1488547036921","appid":"desktop","ip":"0:0:0:0:0:0:0:1","model":"A","time":"2017-04-13 18:47:24","uri":"/api/v2/login","userid":"testuser","make":"CC","status":"SUCCESS"}
{"ca":"2","guid":"23430ec0-9066-11e6-8cd3-3f324f56f302","requestid":"23430ec0-9066-11e6-8cd3-3f324f56f302|1488547328662","appid":"desktop","ip":"0:0:0:0:0:0:0:1","model":"B","time":"2017-04-13 18:52:11","uri":"/api/v2/login","userid":"testuser","make":"CC","status":"SUCCESS"}
{"ca":"2","guid":"23430ec0-9066-11e6-8cd3-3f324f56f302","requestid":"23430ec0-9066-11e6-8cd3-3f324f56f302|1488547616140","appid":"desktop","ip":"0:0:0:0:0:0:0:1","model":"A","time":"2017-04-13 18:56:56","uri":"/api/v2/login","userid":"testuser","make":"CC","status":"SUCCESS"}
{"ca":"2","guid":"23430ec0-9066-11e6-8cd3-3f324f56f302","requestid":"23430ec0-9066-11e6-8cd3-3f324f56f302|1488547700453","appid":"desktop","ip":"0:0:0:0:0:0:0:1","model":"D","time":"2017-04-13 18:58:28","uri":"/api/v2/login","userid":"testuser","make":"CC","status":"SUCCESS"}
{"ca":"2","guid":"23430ec0-9066-11e6-8cd3-3f324f56f302","requestid":"23430ec0-9066-11e6-8cd3-3f324f56f302|1488547719724","appid":"desktop","ip":"0:0:0:0:0:0:0:1","model":"A","time":"2017-04-13 18:58:39","uri":"/api/v2/login","userid":"testuser","make":"CC","status":"SUCCESS"}
{"ca":"2","guid":"23430ec0-9066-11e6-8cd3-3f324f56f302","requestid":"23430ec0-9066-11e6-8cd3-3f324f56f302|1488547768656","appid":"desktop","ip":"0:0:0:0:0:0:0:1","model":"C","time":"2017-04-13 18:59:28","uri":"/api/v2/login","userid":"testuser","make":"CC","status":"SUCCESS"}
```

version:
$ rpm -q google-fluentd
google-fluentd-1.5.13-2.el6.x86_64

**Comment by qingling128** [comment]
Hi @kdabir,

To use `jsonPayload` here, you can make either of the changes below:

1. Change the format in the log file to be 
`{"tag": "<SOME_TAG>", "timestamp": "2017-04-13 18:59:28", "message": {<JSON_HERE>}}`. For example:
`{"tag": "lingshitesting", "message":{"ca":"2","guid":"23430ec0-9066-11e6-8cd3-3c324a56f302","requestid":"23430ec0-9066-11e6-8cd3-3c324a56f302|1488547768656","appid":"desktop","ip":"0:0:0:0:0:0:0:1","model":"C","time":"2017-04-13 18:59:28","uri":"/api/v2/login","userid":"testuser","make":"CC","status":"SUCCESS"}}`.

2. Use a regex in the `format`. For example:
`format /^{"ca":"(?<ca>[^"]*)","guid":"(?<guid>[^"]*)","requestid":"(?<requestid>[^"]*)","appid":"(?<appid>[^"]*)","ip":"(?<ip>[^"]*)","model":"(?<model>[^"]*)","time":"(?<time>[^"]*)","uri":"(?<uri>[^"]*)","userid":"(?<userid>[^"]*)","make":"(?<make>[^"]*)","status":"(?<status>[^"]*)"}/`

**Comment by kdabir** [comment]
Thanks for the help, I am trying with the first option as it does not tie us with the exact order/name of json fields.

By the way, I figured out a small hack to get it to work without requiring the mentioned changes.
If we just add `time_key timestamp` although there is no such field in log line, stackdriver logging starts showing the log as jsonPayload. Bit weird, but worked for me. 

But I am going ahead with first options as thats much better than the hack :)

**Comment by igorpeshansky** [comment]
You could also try using [filter_parser](http://docs.fluentd.org/articles/filter_parser).
