### ISSUE TITLE
v0.14 migration

### ISSUE THREAD

**Issue by cosmo0920** [GoogleCloudPlatform/fluent-plugin-google-cloud#136]
Why not migrate to Fluentd v0.14 API?

* Pros/Cons
  * https://gist.github.com/okkez/05ee6af7b8bb7de852a36eb2f679c344
* Updating plugin for v0.14 from v0.12
  * http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12

* Other Google Cloud Platform services:
  * fluent-plugin-gcs: done
  * fluent-plugin-gcloud-pubsub: will be merged soon
  * fluent-plugin-gcloud-pubsub-custom: done

And 100+ plugins have already been migrated to Fluentd v0.14 plugin API.

If you have questions, feel free to mention to me.

**Comment by igorpeshansky** [comment]
We are waiting for https://github.com/fluent/fluentd/issues/1555 to be fixed before we fully commit to 0.14.

**Comment by cosmo0920** [comment]
https://github.com/fluent/fluentd/pull/1623 should fix fluent/fluentd#1555.
Is it enough to start v0.14 migration?

**Comment by igorpeshansky** [comment]
We just updated our packaging to pull in v0.14.19. We'd like to release that and observe it in the wild for a couple of weeks — if all goes fine, we should be ready to migrate. Ideally, 0.14 would be marked "stable" on the fluentd side first...

**Comment by cosmo0920** [comment]
Fluentd v0.14.22 which is marked as stable release has been released.
https://www.fluentd.org/blog/fluentd-v0.14.22-has-been-released

Is this really enough for v0.14 migration?

**Comment by igorpeshansky** [comment]
Some of our clients are still on v0.12. We're working to address the issues they're having with v0.14. Once we have no more clients using the latest fluent-plugin-google-cloud with v0.12, we'll consider migrating to v0.14.

**Comment by derekperkins** [comment]
Will this work with 1.x?

**Comment by cosmo0920** [comment]
@shusugmt No, this plugin still doesn't use Fluentd v1 native API.

**Comment by qingling128** [comment]
The changes recommended in https://docs.fluentd.org/v1.0/articles/plugin-update-from-v0.12#buffered-output-plugins will need to wait till our next major release to avoid disruptions on the client side. Probably some time next year.

**Comment by apu1111** [comment]
@qingling128 @igorpeshansky 
Any update/timeline for this? I am particularly interested for the multi-worker support.

**Comment by qingling128** [comment]
@apu1111 - Thanks for checking! The `fluent-plugin-google-cloud` output plugin itself already supports multi-worker: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/975357e659a519bfefece1ea2d2ce7791cc1c00d/lib/fluent/plugin/out_google_cloud.rb#L716

As to the next major release cut, it is being evaluated / prioritized in the roadmap now. We are not sure how soon it would be yet though.

**Comment by apu1111** [comment]
@qingling128 - Thanks for the info. We wanted to upgrade to fluentd 1.4 to use `<worker N-M>` directive. Anyway will wait for the next major release.

**Comment by jkohen** [comment]
@qingling128 can you please triage? What value that this provide?

**Comment by qingling128** [comment]
@jkohen The values of this migration is described here: https://gist.github.com/okkez/05ee6af7b8bb7de852a36eb2f679c344.

We have to cut a major release for this though, which we already agreed to do. It's a matter of prioritization.

**Comment by jkohen** [comment]
Are any of the "pros" listed there and the migration itself particularly valuable for Stackdriver users in order to justify doing the migration sooner? It sounds like no, so just confirming. If that's the case, we should close this ticket.

**Comment by qingling128** [comment]
This is now obsolete. See https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent for collecting logs from GCE.
