### ISSUE TITLE
This plugin makes td-agent crash after googleauth gem released 0.5.2 version

### ISSUE THREAD

**Issue by butla** [GoogleCloudPlatform/fluent-plugin-google-cloud#139]
As part of our Ansible scripts, I install td-agent with this plugin [using this Ansible role](https://github.com/William-Yeh/ansible-fluentd).

Recently, td-agent wouldn't get up, because it couldn't load googleauth library. After I manually uninstalled googleaut 0.5.2 and installed 0.5.1 everything started working nicely.

Versions:
td-agent: 0.12.35
fluent-plugin-google-cloud: 0.6.4

System: Ubuntu 16.04.02 on GCE.

I guess this links to [this googleauth issue](https://github.com/google/google-auth-library-ruby/issues/113)

You probably should pin the dependency on googleauth 0.5.1 until they release a new version. Disclaimer: I have near zero knowledge about Ruby and its ecosystem.

**Comment by igorpeshansky** [comment]
Heh, the "unreadable Ruby files" problem hit is too at some point, and we have an explicit workaround for it in our build.
Thanks for the heads-up.

**Comment by dazuma** [comment]
@butla It's indeed possible that the googleauth file permissions are the culprit. To be certain there isn't something else going on, though, can you post any error messages or stack traces you're seeing?

**Comment by dazuma** [comment]
BTW, we just release googleauth 0.5.3 to correct the file permissions issue. Can you please verify?

**Comment by igorpeshansky** [comment]
@qingling128 verified that the upstream fix worked. No action required on our side.

**Comment by butla** [comment]
@dazuma Yep, it's working with the new version.Thanks!
