### ISSUE TITLE
Support kubernetes-specific service name and common labels

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/fluent-plugin-google-cloud#15]
@satnam6502 do you have cycles for this? I can do it if you don't.

@mr-salty

**Comment by mr-salty** [comment]
FYI, the cloud logging API currently only accepts a known set of service names and labels so we will need to add support for this on the backend (and wait for the next weekly release) before doing anything on the plugin.  @andreweames

**Comment by mr-salty** [comment]
OK, Cloud Logging API support for this is in place, so we can modify the plugin at will..

service: "container.googleapis.com";
primary label: "container.googleapis.com/cluster";
secondary label: "container.googleapis.com/namespace";

**Comment by mr-salty** [comment]
@a-robinson - fixed?

**Comment by a-robinson** [comment]
Yes -- I'll send another PR soon to fall back to just populating cluster name, namespace name, pod name, and container name in the case that the metadata plugin isn't being used, but this can be considered done.
