### ISSUE TITLE
Failing to load monitoring.rb on version 0.6.5

### ISSUE THREAD

**Issue by butla** [GoogleCloudPlatform/fluent-plugin-google-cloud#150]
Hi! It's me again (#139). This time the file monitoring.rb (which for me, after the installation of td-agent resides in `/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-google-cloud-0.6.5/lib/fluent/plugin`) misses a readable flag for all other users, so it fails to load when `td-agent` user tries to do it. Which in turn crashes td-agent.

Running `sudo chmod +r` on the file fixes the issue.

In #139 the issue was fixed by issuing a new release with a fixed access modifier on the file.

**Comment by butla** [comment]
It's the same in 0.6.6...

**Comment by igorpeshansky** [comment]
Fixed via 1b40072fc9cbf38fc4f8776502ad8600849ef242.

**Comment by butla** [comment]
@igorpeshansky Thanks for that :)
