### ISSUE TITLE
Failed to start LSB: data collector for Treasure Data

### ISSUE THREAD

**Issue by sanjivr007** [GoogleCloudPlatform/fluent-plugin-google-cloud#157]
This is my ruby plugin code which I am trying to add .
```ruby
require 'fluent/mixin/rewrite_tag_name'

class Fluent::GraphiteOutput < Fluent::Output
  Fluent::Plugin.register_output('graphite', self)

  include Fluent::HandleTagNameMixin
  include Fluent::Mixin::RewriteTagName

  config_param :host, :string
  config_param :port, :integer, default: 2003
  config_param :tag_for, :string, default: 'prefix'
  config_param :name_keys, :string, default: nil
  config_param :name_key_pattern, :string, default: nil

  unless method_defined?(:log)
    define_method(:log) { $log }
  end

  def initialize
    super
    require 'graphite-api'
  end

  def start
    super
    connect_client!
  end

  def configure(conf)
    super

    if !['prefix', 'suffix', 'ignore'].include?(@tag_for)
      raise Fluent::ConfigError, 'out_graphite: can specify to tag_for only prefix, suffix or ignore'
    end

    if !@name_keys && !@name_key_pattern
      raise Fluent::ConfigError, 'out_graphite: missing both of name_keys and name_key_pattern'
    end
    if @name_keys && @name_key_pattern
      raise Fluent::ConfigError, 'out_graphite: cannot specify both of name_keys and name_key_pattern'
    end

    if @name_keys
      @name_keys = @name_keys.split(',')
    end
    if @name_key_pattern
      @name_key_pattern = Regexp.new(@name_key_pattern)
    end
    # How many times to retry the call if timeout raised
    @max_retries ||= 3
  end

  def emit(tag, es, chain)
    es.each do |time, record|
      emit_tag = tag.dup
      filter_record(emit_tag, time, record)
      next unless metrics = format_metrics(emit_tag, record)

      # implemented to immediate call post method in this loop, because graphite-api.gem has the buffers.
      
      post(metrics, time)
    end

    chain.next
  end

  def format_metrics(tag, record)
    filtered_record = if @name_keys
                        record.select { |k,v| @name_keys.include?(k.to_s) }
                      else # defined @name_key_pattern
                        record.select { |k,v| @name_key_pattern.match(k.to_s) }
                      end

    return nil if filtered_record.empty?

    metrics = {}
    tag = tag.sub(/\.$/, '') # may include a dot at the end of the emit_tag fluent-mixin-rewrite-tag-name returns. remove it.
    key=""
    value=0
    filtered_record.each do |k, v|
     log.warn "Key Value #{k} #{v}"
     if (k.to_s).eql? @name_keys[0]
        key = case @tag_for
            when 'ignore' then k.to_s
            when 'prefix' then "#{tag}.#{v}"
            when 'suffix' then "#{v}.#{tag}"
            end

        key = key.gsub(/(\s|\/)+/, '_') # cope with in the case of containing symbols or spaces in the key of the record like in_dstat.
      elsif (k.to_s).eql? @name_keys[1]
        value=v.to_i
       # key=key+v
      end     
    end 
    #log.warn "break #{key} #{value}"
    metrics[key] = value  
    #log.warn "break2 #{metrics}"  
    metrics
  end

  def post(metrics, time)
    #log.warn "break3 #{metrics} #{time}"
    trial ||= 1
    #connector = GraphiteAPI::Connector.new("localhost",2003)

    #metrics.each do |key, value|
     #    toSendString = "#{key} #{value} #{time}"
     #    log.warn "#{toSendString}"
     #    connector.puts(toSendString)
         #puts "#{key}-----"
         #puts array
    #end
    
    @client.metrics(metrics, time)
  rescue Errno::ETIMEDOUT
    # after long periods with nothing emitted, the connection will be closed and result in timeout
    if trial <= @max_retries
      log.warn "out_graphite: connection timeout to #{@host}:#{@port}. Reconnecting... "
      trial += 1
      connect_client!
      retry
    else
      log.error "out_graphite: ERROR: connection timeout to #{@host}:#{@port}. Exceeded max_retries #{@max_retries}"
    end
  rescue Errno::ECONNREFUSED
    log.warn "out_graphite: connection refused by #{@host}:#{@port}"
  rescue SocketError => se
    log.warn "out_graphite: socket error by #{@host}:#{@port} :#{se}"
  rescue StandardError => e
    log.error "out_graphite: ERROR: #{e}"
  end
  
  def connect_client!
    @client = GraphiteAPI.new(graphite: "#{@host}:#{@port}")
  end
end
```
Ubuntu -16.04

error- 
```
-- Unit td-agent.service has begun starting up.
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]: Starting td-agent: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_r
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /etc/td-agent/plugin/plugin.rb:1:in `<top (required)>'
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugi
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugi
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugi
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engin
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/super
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/comma
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/bin/fluentd:5:in
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /usr/sbin/td-agent:7:in `load'
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:         from /usr/sbin/td-agent:7:in `<main>'
Sep 08 20:01:12 ip-172-31-63-173 td-agent[24355]:  * td-agent
Sep 08 20:01:12 ip-172-31-63-173 systemd[1]: td-agent.service: Control process exited, code=exited status=1
Sep 08 20:01:12 ip-172-31-63-173 systemd[1]: Failed to start LSB: data collector for Treasure Data.
-- Subject: Unit td-agent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit td-agent.service has failed.
-- 
-- The result is failed.
Sep 08 20:01:12 ip-172-31-63-173 systemd[1]: td-agent.service: Unit entered failed state.
Sep 08 20:01:12 ip-172-31-63-173 systemd[1]: td-agent.service: Failed with result 'exit-code'.
Sep 08 20:01:12 ip-172-31-63-173 sudo[24344]: pam_unix(sudo:session): session closed for user root
```
Please help

**Comment by sanjivr007** [comment]
My plugin trying to read data from nginx access log and push data in graphite

**Comment by sanjivr007** [comment]
td-agent 0.12.35 
gem version - 2.6.11
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by sanjivr007** [comment]
sudo /usr/sbin/td-agent-gem list

*** LOCAL GEMS ***

actionmailer (4.2.8)
actionpack (4.2.8)
actionview (4.2.8)
activejob (4.2.8)
activemodel (4.2.8)
activerecord (4.2.8)
activesupport (4.2.8)
addressable (2.5.1)
arel (6.0.4)
aws-sdk (2.9.9)
aws-sdk-core (2.9.9)
aws-sdk-resources (2.9.9)
aws-sigv4 (1.0.0)
bigdecimal (1.2.4)
bson (4.1.1)
builder (3.2.3)
bundler (1.14.5)
bzip2-ffi (1.0.0)
celluloid (0.15.2)
cool.io (1.4.6)
diff-lcs (1.3)
draper (1.4.0)
erubis (2.7.0)
ffi (1.9.18)
fluent-logger (0.7.1)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-kafka (0.5.5)
fluent-plugin-mongo (0.8.0)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-s3 (0.8.2)
fluent-plugin-scribe (0.10.14)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-webhdfs (0.4.2)
fluentd (0.12.35)
fluentd-ui (0.4.4)
font-awesome-rails (4.7.0.1)
globalid (0.4.0)
haml (4.0.7)
haml-rails (0.5.3)
hike (1.2.3)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
i18n (0.8.1)
io-console (0.4.3)
ipaddress (0.8.3)
jbuilder (2.6.3)
jmespath (1.3.1)
jquery-rails (3.1.4)
json (1.8.1)
kramdown (1.13.2)
kramdown-haml (0.0.3)
loofah (2.0.3)
ltsv (0.1.0)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitest (5.10.1, 4.7.5)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
mongo (2.2.7)
msgpack (1.0.3)
multi_json (1.12.1)
nokogiri (1.7.1)
ohai (6.20.0)
oj (2.18.1)
parallel (1.8.0)
psych (2.0.5)
public_suffix (2.0.5)
puma (3.8.2)
rack (1.6.5)
rack-test (0.6.3)
rails (4.2.8)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.8)
rails-html-sanitizer (1.0.3)
railties (4.2.8)
rake (10.1.0)
rdoc (4.1.0)
request_store (1.3.2)
ruby-kafka (0.3.17)
ruby-progressbar (1.8.1)
rubyzip (1.2.1, 1.1.7)
sass (3.2.19)
sass-rails (4.0.5)
settingslogic (2.0.9)
sigdump (0.2.4)
sprockets (2.12.4)
sprockets-rails (2.3.3)
string-scrub (0.0.5)
sucker_punch (1.0.5)
systemu (2.5.2)
td (0.15.2)
td-client (0.8.85)
td-logger (0.3.26)
test-unit (2.1.10.0)
thor (0.19.4)
thread_safe (0.3.6)
thrift (0.8.0)
tilt (1.4.1)
timers (1.1.0)
tzinfo (1.2.3)
tzinfo-data (1.2017.2)
uuidtools (2.1.5)
webhdfs (0.8.0)
yajl-ruby (1.3.0)
zip-zip (0.3)

cat /var/log/td-agent/td-agent.log


2017-09-08 20:08:22 +0000 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2017-09-08 20:08:22 +0000 [info]: starting fluentd-0.12.35
2017-09-08 20:08:22 +0000 [info]: process finished code=256
2017-09-08 20:08:22 +0000 [warn]: process died within 1 second. exit.

cat /etc/td-agent/td-agent.conf


<match td.*.*>
  @type tdlog
  apikey YOUR_API_KEY

  auto_create_table
  buffer_type file
  buffer_path /var/log/td-agent/buffer/td

  <secondary>
    @type file
    path /var/log/td-agent/failed_records
  </secondary>
</match>

## match tag=debug.** and dump to console
<match debug.**>
  @type stdout
</match>

####
## Source descriptions:
##

## built-in TCP input
## @see http://docs.fluentd.org/articles/in_forward
<source>
  @type forward
</source>

## built-in UNIX socket input
#<source>
#  @type unix
#</source>

# HTTP input
# POST http://localhost:8888/<tag>?json=<json>
# POST http://localhost:8888/td.myapp.login?json={"user"%3A"me"}
# @see http://docs.fluentd.org/articles/in_http
<source>
  @type http
  port 8888
</source>

## live debugging agent
<source>
  @type debug_agent
  bind 127.0.0.1
  port 24230
</source>

<source>
  @type tail
  path /var/log/nginx/access.log
  pos_file /var/log/nginx/access.log.pos
  format /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$/
  time_format %d/%b/%Y:%H:%M:%S %z
  tag metrics.nginxQa
</source>

<match **>
  type graphite
  host gra*********************
  port 2003
  tag_for prefix
  name_keys path,code
</match>

**Comment by sanjivr007** [comment]
Did some changes now error got changed -

2017-09-08 21:16:01 +0000 [error]: #0 cannot load such file -- graphite-api path="graphite-api" error_class=LoadError error="cannot load such file -- graphite-api"
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-09-08 21:16:01 +0000 [error]: #0 /etc/td-agent/plugin/out_graphite.rb:22:in `initialize'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/plugin.rb:149:in `new'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/plugin.rb:149:in `new_impl'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/plugin.rb:104:in `new_output'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/agent.rb:128:in `add_match'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/agent.rb:72:in `block in configure'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/agent.rb:64:in `each'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/agent.rb:64:in `configure'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:109:in `configure'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/engine.rb:127:in `configure'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/engine.rb:92:in `run_configure'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:733:in `run_configure'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:502:in `block in run_worker'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:661:in `main_process'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:498:in `run_worker'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/bin/fluentd:5:in `<top (required)>'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/bin/fluentd:22:in `load'
  2017-09-08 21:16:01 +0000 [error]: #0 /opt/td-agent/embedded/bin/fluentd:22:in `<top (required)>'
  2017-09-08 21:16:01 +0000 [error]: #0 /usr/sbin/td-agent:7:in `load'
  2017-09-08 21:16:01 +0000 [error]: #0 /usr/sbin/td-agent:7:in `<main>'
2017-09-08 21:16:02 +0000 [info]: Worker 0 finished unexpectedly with status 2

**Comment by igorpeshansky** [comment]
None of your errors mention this plugin (`fluent-plugin-google-cloud`) or the associated `google-fluentd` package. Sorry, but this is an unrelated issue that you should report against [`td-agent`](https://github.com/treasure-data/td-agent). If it turns out that our plugin was at fault, please reopen.

**Comment by longrenren** [comment]
‘rm /lib/systemd/system/td-agent.service’
It works

**Comment by shashanktyagi3192** [comment]
Not working for me.. getting the same error
Unit td-agent.service entered failed state.
Dec 04 13:02:24 ip-172-31-51-116.ec2.internal systemd[1]: td-agent.service failed.
Dec 04 13:02:24 ip-172-31-51-116.ec2.internal polkitd[514]: Unregistered Authentication Agent for unix-process:10967:1672027 (system bu
Dec 04 13:04:20 ip-172-31-51-116.ec2.internal polkitd[514]: Registered Authentication Agent for unix-process:11010:1683598 (system bus 
Dec 04 13:04:20 ip-172-31-51-116.ec2.internal systemd[1]: Starting LSB: data collector for Treasure Data...

**Comment by sanjivr007** [comment]
If u will tell what all steps you are following and your host machine
specification then I can help you to configure it.

**Comment by artemas** [comment]
Got it after apt upgrade, removed current google-fluentd.conf, but still is not working:

```
Setting up google-fluentd (1.5.28-1) ...
Installing default conffile /etc/google-fluentd/google-fluentd.conf ...
Job for google-fluentd.service failed because the control process exited with error code. See "systemctl status google-fluentd.service" and "journalctl -xe" for details.
invoke-rc.d: initscript google-fluentd, action "start" failed.
● google-fluentd.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/init.d/google-fluentd; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-03-02 22:01:29 UTC; 6ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 11198 ExecStart=/etc/init.d/google-fluentd start (code=exited, status=1/FAILURE)

Mar 02 22:01:28 myserver systemd[1]: Starting LSB: data collector for Treasure Data...
Mar 02 22:01:29 myserver google-fluentd[11198]: Starting google-fluentd 1.5.28:  * google-fluentd
Mar 02 22:01:29 myserver systemd[1]: google-fluentd.service: Control process exited, code=exited status=1
Mar 02 22:01:29 myserver systemd[1]: Failed to start LSB: data collector for Treasure Data.
Mar 02 22:01:29 myserver systemd[1]: google-fluentd.service: Unit entered failed state.
Mar 02 22:01:29 myserver systemd[1]: google-fluentd.service: Failed with result 'exit-code'.
dpkg: error processing package google-fluentd (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of google-fluentd-catch-all-config:
 google-fluentd-catch-all-config depends on google-fluentd (>= 1.3.0); however:
  Package google-fluentd is not configured yet.

dpkg: error processing package google-fluentd-catch-all-config (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 google-fluentd
 google-fluentd-catch-all-config
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by igorpeshansky** [comment]
This is a different issue, so I wish you'd've opened a new one... But we might as well use this one to track now.

I suspect you're running into an upgrade problem. You'll probably see something like this in `/var/log/google-fluentd/google-fluent.log`:
```
2018-02-23 20:01:05 +0000 [error]: config error file="/etc/google-fluentd/google-fluentd.conf" error_class=Fluent::ConfigError error="Other 'in_tail' plugin already use same pos_file path: plugin_id = object:3fa7e7fb9220, pos_file path = /var/lib/google-fluentd/pos/puppet-masterhttp.pos"
```
We're working on a fix. A workaround is to overwrite `/etc/google-fluentd/config.d/puppet-enterprise.conf` and restart the service:
```
$ sudo cp /etc/google-fluentd/config.d/puppet-enterprise.conf.dpkg-new /etc/google-fluentd/config.d/puppet-enterprise.conf
$ sudo service google-fluentd restart
```

@qingling128 FYI.

**Comment by jkohen** [comment]
This is an old issue, so closing. Please reopen if you still need help with this particular problem.

**Comment by chetan-happyness** [comment]
Hi @jkohen  I m having saving same issue, need help 
 google-fluentd.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/init.d/google-fluentd; generated)
  Process: 19737 ExecStart=/etc/init.d/google-fluentd start (code=exited, status=1/FAILURE)
Nov 22 10:55:59 ip-172-31-45-41 google-fluentd[19737]:         from /usr/sbin/google-fluentd:7:in `load'
Nov 22 10:55:59 ip-172-31-45-41 google-fluentd[19737]:         from /usr/sbin/google-fluentd:7:in `<main>'
Nov 22 10:55:59 ip-172-31-45-41 google-fluentd[19737]:  * google-fluentd
Nov 22 10:55:59 ip-172-31-45-41 systemd[1]: google-fluentd.service: Control process exited, code=exited status=1
Nov 22 10:55:59 ip-172-31-45-41 systemd[1]: google-fluentd.service: Failed with result 'exit-code'.
Nov 22 10:55:59 ip-172-31-45-41 systemd[1]: Failed to start LSB: data collector for Treasure Data.
dpkg: error processing package google-fluentd (--configure):
 installed google-fluentd package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of google-fluentd-catch-all-config:
 google-fluentd-catch-all-config depends on google-fluentd (>= 1.3.0); however:
  Package google-fluentd is not configured yet.

**Comment by chetan-happyness** [comment]
Having same issue on aws ubuntu instance (18.04)

`
 google-fluentd.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/init.d/google-fluentd; generated)
  Process: 19737 ExecStart=/etc/init.d/google-fluentd start (code=exited, status=1/FAILURE)
Nov 22 10:55:59 ip-172-31-45-41 google-fluentd[19737]:         from /usr/sbin/google-fluentd:7:in `load'
Nov 22 10:55:59 ip-172-31-45-41 google-fluentd[19737]:         from /usr/sbin/google-fluentd:7:in `<main>'
Nov 22 10:55:59 ip-172-31-45-41 google-fluentd[19737]:  * google-fluentd
Nov 22 10:55:59 ip-172-31-45-41 systemd[1]: google-fluentd.service: Control process exited, code=exited status=1
Nov 22 10:55:59 ip-172-31-45-41 systemd[1]: google-fluentd.service: Failed with result 'exit-code'.
Nov 22 10:55:59 ip-172-31-45-41 systemd[1]: Failed to start LSB: data collector for Treasure Data.
dpkg: error processing package google-fluentd (--configure):
 installed google-fluentd package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of google-fluentd-catch-all-config:
 google-fluentd-catch-all-config depends on google-fluentd (>= 1.3.0); however:
  Package google-fluentd is not configured yet.
`

**Comment by jkohen** [comment]
@chetan-happyness please open a new issue and add enough details so we can assist you. If it's available to you, you should use the Google Cloud Support channel, who work with us to give you the best support experience.
