### ISSUE TITLE
Add Multi Worker Support

### ISSUE THREAD

**Issue by GLStephen** [GoogleCloudPlatform/fluent-plugin-google-cloud#164]
FluentD now supports multiworkers, but this plugin does not. I have other plugins we are using inside google-fluentd and machine utilization would be better in multi-worker. This plugin is holding up enabling it. Is this something that can be resolved?

**Comment by igorpeshansky** [comment]
Thanks for the report. This is on our roadmap, but we have no concrete timelines just yet. We'll update this issue when we do.
We are also an open-source project and accept pull requests if you choose to contribute.

**Comment by GLStephen** [comment]
@igorpeshansky in high volume scenarios it can be hard to fully load a box if google-fluentd is part of the pipeline. A multicore web server will saturate a single core very quickly leaving the others relatively idle in terms of web processing.

The process for making the plugin multi-worker is really simple. I could make a PR very quickly. The complexity is whether there is anything in the plugin that conflicts with a multi-worker setup. Any shared data, etc. which is harder for someone, like myself, who is not intimately aware of the plugin to know about.

I can submit the code change, will you all code review it and run through testing?

**Comment by igorpeshansky** [comment]
@GLStephen yes, we will.  We may need to restructure our tests to allow running with multiple workers, but it would be good to have a starting point.
Out of curiosity, what part of fluentd processing is CPU-bound for you? Log parsing and transformations? Because this output plugin is, for the most part, I/O-bound.

**Comment by GLStephen** [comment]
@igorpeshansky we are running other plugins through google-fluentd. We would like to run them multi worker but have this plugin in the mix too.

**Comment by cosmo0920** [comment]
To support this feature, we should do v0.14 migration. #136

**Comment by qingling128** [comment]
With other blockers resolved, we were able to make the flip: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/296
