### ISSUE TITLE
How to catch severity from JSON log files?

### ISSUE THREAD

**Issue by unbornchikken** [GoogleCloudPlatform/fluent-plugin-google-cloud#166]
Hi,

We have a pretty standard logging system that uses [bunyan](https://github.com/trentm/node-bunyan) to write out some json log files.

For example, a log file cosist of lines like the following:

```json
{
"process":"host",
"hostname":"mezo-g-w10",
"pid":4160,
"level":20,
"msg":"Application has been started.",
"time":"2017-10-11T12:42:46.549Z",
"v":0
}
```

Please note that bunyan writes log severity as a number those could be transformed to standard info, warning, error, etc severity levels.

We process that with the following fluentd configuration:

```xml
<source>
        @type tail
        format json
        time_key time
        path /bimbo/Logs/host.log
        time_format %Y-%m-%dT%H:%M:%S.%LZ
        encoding UTF-8
        tag portal.host
</source>

<filter portal.*>
        @type record_transformer
        enable_ruby
        <record>
                severity ${ if record["level"] == 60 then "CRITICAL" elsif record["level"] == 50 then "ERROR" elsif record["level"] == 40 then "WARNING" elsif record["level"] == 30 then "INFO" elsif record["level"] == 20 then "DEBUG" elsif record["level"] == 10 then "DEBUG" end}
        </record>
</filter>
```

So the json gets parsed then `level` field gets converted to `severity` by using values that Google Stackdriver should understand.

The problem is, Stackdriver doesn't understand the transformed `severity` field by this way. I believe it should be part of the header instead of the record, so it should somehow get parsed and transformed in the `trail` to be a `severity` field in first place.

My question is, how we should do this? How we make Stackdriver understand bunyan's `level` field as `severity`?

**Comment by igorpeshansky** [comment]
The Stackdriver output plugin does understand numeric severity values, so you shouldn't have to convert.
As for why it doesn't see the `severity` field, we'd have to investigate. We need to see your whole fluentd config, including the output plugin config. Are you installing the agent package we distribute, or the output plugin gem directly? If the former, what is the package version? If the latter, what version of the gem, and what other gems do you have installed?

**Comment by unbornchikken** [comment]
We're using it in Kubernetes, and we wanted to see our logs by aggregated along with cluster logs, so the source is stdout.

The relevant part of the whole config is the following:

```xml
<source>
        @type tail
        format json
        time_key time
        path /bimbo/Logs/host.log
        time_format %Y-%m-%dT%H:%M:%S.%LZ
        encoding UTF-8
        tag portal.host
</source>

<filter portal.*>
        @type record_transformer
        enable_ruby
        <record>
                severity ${ if record["level"] == 60 then "CRITICAL" elsif record["level"] == 50 then "ERROR" elsif record["level"] == 40 then "WARNING" elsif record["level"] == 30 then "INFO" elsif record["level"] == 20 then "DEBUG" elsif record["level"] == 10 then "DEBUG" end}
        </record>
</filter>

<match **>
        @type stdout
</match>
```

So the parsed and tranformed entries gets written to stdout and gets collected by Kubernetes agent. By this way once the record gets arrived in Stackdriver it has the severity field, we can see it in the online Log Viever as the part of the record, but somehow it doesn't get understood as real severity, all of our entries are thread as "Info".

**Comment by igorpeshansky** [comment]
Ah, so you run a fluentd sidecar that transforms your log file and dumps each record to `stdout` as JSON, and then you let the Kubernetes fluentd pick that up from the container's `stdout`? Do you have a sample of the log lines that you actually see ingested?
Note that #4 asks for adding a `severity_key` option, but that won't help you in Kubernetes, unless you override the default config as described in https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver/.

**Comment by unbornchikken** [comment]
Lemme summon @tankovicsg to our conversation, he knows the actual setup better tank me. @tankovicsg please advise regarding the above. Ty.

**Comment by tankovicsg** [comment]
So the main problem was we lost a json format on stdout however it was set. 
Finally we drop that sidecar approach. So this issue is not already relevant. The story is continued in #175

**Comment by igorpeshansky** [comment]
Looks like this can be closed?
@tankovicsg @unbornchikken

**Comment by tankovicsg** [comment]
@igorpeshansky do it!

**Comment by igorpeshansky** [comment]
Thanks. In case you want to revisit this in the future, there's still the open question of:
> Do you have a sample of the log lines that you actually see ingested?
Technically, your `record_transformer` setup _ought_ to have worked, but we'd need to debug with sample data.
