### ISSUE TITLE
Support overwriting tag with 'tag' key in record

### ISSUE THREAD

**Issue by hoozecn** [GoogleCloudPlatform/fluent-plugin-google-cloud#17]
it would be wonderful if we can overwrite the tag value with the 'tag' value in message

**Comment by mr-salty** [comment]
Hi - sorry for the delayed response, but could you accomplish this with the rewrite_tag plugin? http://docs.fluentd.org/articles/out_rewrite_tag_filter

**Comment by hoozecn** [comment]
@mr-salty Thanks for the reply.

It works well with out_rewrite_tag_filter and the following configuration.

Thanks man.

-------
fluentd.conf
```
<source>
  type udp
  tag gsc.udp
  port 8514
  format json
  time_key time
  time_format %Y-%m-%d %H:%M:%S
</source>
<match fluent.**>
  type null
</match>
<match gsc.*>
  type rewrite_tag_filter
  rewriterule1 message \[(\w+)\] $1
</match>
<match **>
  type google_cloud
  buffer_chunk_limit 512K
  flush_interval 5s
  max_retry_wait 300
  disable_retry_limit
</match>
```
-------
log a message
```
nc -u 127.0.0.1 8514
{"message":"[test]"}
```

------

result:

The message will go to logger "test".
