### ISSUE TITLE
Detecting the platform based on METADATA_SERVICE_ADDR API response header is not working on some AWS instancetype

### ISSUE THREAD

**Issue by baskaran-md** [GoogleCloudPlatform/fluent-plugin-google-cloud#182]
**Error:**
```
2017-11-24 21:27:40 +0000 [info]: plugin/out_google_cloud.rb:737:detect_platform: Unable to determine platform
2017-11-24 21:27:40 +0000 [error]: fluent/supervisor.rb:540:rescue in dry_run: config error file="/opt/apigee/data/apigee-logger/google-fluentd.conf" error_class=Fluent::ConfigError error="Unable to obtain metadata parameters: zone vm_id"
```

Some of the new instance families like **c5.9xlarge**, doesn't return the same response headers like the other instance types. 

```
[root@node baskaran.md]# curl -s http://169.254.169.254 -I
HTTP/1.1 200 OK
Connection: close
Content-Type: text/plain
```

However, on other instances like **c3.large,** 
```
[root@node baskaran.md]# curl http://169.254.169.254/ -I
HTTP/1.0 200 OK
Content-Type: text/plain
Accept-Ranges: bytes
ETag: "2990503662"
Last-Modified: Thu, 09 Nov 2017 04:08:37 GMT
Content-Length: 197
Connection: close
Date: Fri, 24 Nov 2017 04:05:13 GMT
Server: EC2ws
```

So relying on the `Server` response header to identify the platform is not foolproof. Instead, can we fallback to another check like below?
**Ref:** http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-categories

```
[root@node baskaran.md]# curl http://169.254.169.254/latest/meta-data/services/domain -i
HTTP/1.1 200 OK
Connection: close
Content-Type: text/plain

amazonaws.com
```

Meanwhile, I am following up with Amazon Support to understand more on the response headers of those APIs.

**Comment by igorpeshansky** [comment]
Thank you, please keep us posted on what you find out from AWS support.

**Comment by baskaran-md** [comment]
AWS Support was able to reproduce the issue, and they have assigned the ticket to internal team to investigate more. 

I am also checking with them on the reliability of `services/domain` resource. Will post back their response here.

**Comment by baskaran-md** [comment]
Amazon has deployed a fix on their server side to include the default headers in the response of metadata.

Now the response from c5.9xlarge instances matches to the c3.large (as specified in https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/182#issue-276701787)
```
[root@node baskaran.md]# curl http://169.254.169.254/ -I
HTTP/1.1 200 OK
Content-Type: text/plain
Accept-Ranges: none
Last-Modified: Thu, 28 Dec 2017 17:47:22 GMT
Content-Length: 197
Date: Thu, 28 Dec 2017 19:10:12 GMT
Server: EC2ws
Connection: close```

Its good to close the pull request.
