### ISSUE TITLE
Authentication is broken in latest release

### ISSUE THREAD

**Issue by eastlondoner** [GoogleCloudPlatform/fluent-plugin-google-cloud#197]
The official google-fluentd logger fails to authenticate with stack driver since the 0.6.11 release.

This happens on instances in AWS EC2. Our instances are pretty basic instances running Debian Linux 9.2

We install google-fluentd using the script at https://dl.google.com/cloudagents/install-logging-agent.sh

Our systems have been working fine until the 0.6.11 release yesterday.

If we look in the logs here:
`less /var/log/google-fluentd/google-fluentd.log`

We now see:
```
Dropping 130 log message(s) error="16:#<Signet::AuthorizationError: Authorization failed.  Server message:\n{\n \"error\": \"invalid_
scope\",\n \"error_description\": \"Invalid downscoping, scopes should not be specified as a request parameter.\"\n}>" error_code="16"
```

I can fix it by reverting to 0.6.10 using the following commands:

` sudo /opt/google-fluentd/embedded/bin/fluent-gem uninstall fluent-plugin-google-cloud googleauth google-cloud-logging`

`sudo /opt/google-fluentd/embedded/bin/fluent-gem install fluent-plugin-google-cloud -v 0.6.10`

This reproduces consistently.

**Comment by igorpeshansky** [comment]
This is likely caused by #179.

**Comment by Stelminator** [comment]
I ran into this as well, also on EC2, debian.  Thanks @eastlondoner for the workaround while waiting for a new build of google-fluentd.

**Comment by igorpeshansky** [comment]
I've just pushed version 0.6.12 of the gem that should fix the problem. Could you please install that and verify that it works for you while I release the new `google-fluentd` package?

**Comment by Stelminator** [comment]
I had just started to rebuild some things.  I've switched my patch to say ".12" instead of ".10".  I will verify that .11 still breaks when things come back up.

**Comment by igorpeshansky** [comment]
Thanks. I'll yank 0.6.11 as soon as the new google-fluentd version is pushed.

**Comment by Stelminator** [comment]
well, my script didn't work the way I wanted, but, anyway, 0.6.12 makes things work again.

**Comment by igorpeshansky** [comment]
Thanks for confirming. The new `google-fluentd` package will be released tonight or tomorrow.

**Comment by qingling128** [comment]
The new `google-fluentd` package has been released. Also fluent-plugin-google-cloud `v0.6.11` has been yanked.
