### ISSUE TITLE
Debian 9 (stretch) google-fluentd support

### ISSUE THREAD

**Issue by AndryBray** [GoogleCloudPlatform/fluent-plugin-google-cloud#199]
We can't upgrade our Vms on kubernetes because google-fluentd logging agent is not supported on Debian 9.
Here the details of issue:
https://stackoverflow.com/questions/47838777/google-fluentd-error-on-debian-stretch-google-logging-agent

**Comment by igorpeshansky** [comment]
The agent does support Debian 9 (stretch). We'll update the documentation.
There isn't enough information in the StackOverflow issue. Do you get any other errors prior to the "GPG error"? The script is supposed to run `apt-key add`.
What is the full output of the docker image build?

**Comment by AndryBray** [comment]
Installing agents for Debian or Ubuntu.
install-logging-agent.sh: line 94: lsb_release: command not found
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
W: GPG error: http://packages.cloud.google.com/apt google-cloud-logging-wheezy InRelease: The following signatures couldn't be verified because the
 public key is not available: NO_PUBKEY 3746C208A7317B0F
W: The repository 'http://packages.cloud.google.com/apt google-cloud-logging-wheezy InRelease' is not signed.
WARNING: The following packages cannot be authenticated!
  google-fluentd google-fluentd-catch-all-config
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
dpkg-query: no packages found matching google-fluentd
google-fluentd: unrecognized service
grep: /var/log/google-fluentd/google-fluentd.log: No such file or directory

**Comment by AndryBray** [comment]
any news about this problem? it's blocking us from upgrading to latest stable debian

**Comment by qingling128** [comment]
Hi @AndryBray,

I just doubled checked the installation on Debian GNU/Linux 9 (stretch). I could not reproduce the issue though.

```
$ sudo curl -sSO https://dl.google.com/cloudagents/install-logging-agent.sh && sudo bash install-logging-agent.sh
==============================================================================
Starting installation of google-fluentd
==============================================================================

Installing agents for Debian or Ubuntu.
OK
Selecting previously unselected package google-fluentd.
(Reading database ... 31303 files and directories currently installed.)
Preparing to unpack .../google-fluentd_1.5.24-2_amd64.deb ...
Unpacking google-fluentd (1.5.24-2) ...
Selecting previously unselected package google-fluentd-catch-all-config.
Preparing to unpack .../google-fluentd-catch-all-config_0.6_all.deb ...
Unpacking google-fluentd-catch-all-config (0.6) ...
Setting up google-fluentd (1.5.24-2) ...
Adding system user `google-fluentd' (UID 108) ...
Adding new group `google-fluentd' (GID 112) ...
Adding new user `google-fluentd' (UID 108) with group `google-fluentd' ...
Not creating home directory `/home/google-fluentd'.
Installing default conffile /etc/google-fluentd/google-fluentd.conf ...
Setting up google-fluentd-catch-all-config (0.6) ...

==============================================================================
Installation of google-fluentd complete.

Logs from this machine should be visible in the log viewer at:
  https://console.cloud.google.com/logs/viewer?project=google.com:sandbox-146415&resource=gce_instance/instance_id/7563828836626758444

A test message has been sent to syslog to help verify proper operation.

Please consult the documentation for troubleshooting advice:
  https://cloud.google.com/logging/docs/agent

You can monitor the logging agent's logfile at:
  /var/log/google-fluentd/google-fluentd.log
==============================================================================
lingshi@debian9:~$ sudo service google-fluentd status
● google-fluentd.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/init.d/google-fluentd; generated; vendor preset: enabled)
   Active: active (running) since Mon 2018-01-08 19:28:40 UTC; 57s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1160 ExecStop=/etc/init.d/google-fluentd stop (code=exited, status=0/SUCCESS)
  Process: 1586 ExecStart=/etc/init.d/google-fluentd start (code=exited, status=0/SUCCESS)
    Tasks: 104 (limit: 4915)
   CGroup: /system.slice/google-fluentd.service
           ├─1616 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd --log /var/log/google-fluentd/google-fluentd.log --daemon /var/run/google-fluentd/goog
le-fluentd.pid
           └─1621 /opt/google-fluentd/embedded/bin/ruby -Eascii-8bit:ascii-8bit /usr/sbin/google-fluentd --log /var/log/google-fluentd/google-fluentd.log --daemon /var
/run/google-fluentd/google-fluentd.pid --under-supervisor

Jan 08 19:28:39 debian9 systemd[1]: Stopped LSB: data collector for Treasure Data.
Jan 08 19:28:39 debian9 systemd[1]: Starting LSB: data collector for Treasure Data...
Jan 08 19:28:40 debian9 google-fluentd[1586]: Starting google-fluentd 1.5.24: google-fluentd.
Jan 08 19:28:40 debian9 systemd[1]: Started LSB: data collector for Treasure Data.
```

What does `lsb_release -c` show in your case? If it's not available (it should be installed by default though), can you try `apt-get install lsb-release`?

**Comment by AndryBray** [comment]
Hi @qingling128 
I was trying to install it on docker image php:7.2.0-apache
https://github.com/docker-library/php/blob/f4baf0edbc4e05e241938c68bcc7c9635707583d/7.2/stretch/apache/Dockerfile

Is it enough for you to check again?
Thanks

**Comment by AndryBray** [comment]
@qingling128  I've just tried to run again with php-7.2.1-apache but it doesn't work.

I had to add "apt-get install lsb-release" because not found on this image.

`==============================================================================
Starting installation of google-fluentd
==============================================================================

Installing agents for Debian or Ubuntu.
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
W: GPG error: http://packages.cloud.google.com/apt google-cloud-logging-wheezy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3746C208A7317B0F
W: The repository 'http://packages.cloud.google.com/apt google-cloud-logging-wheezy InRelease' is not signed.
WARNING: The following packages cannot be authenticated!
  google-fluentd google-fluentd-catch-all-config
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
dpkg-query: no packages found matching google-fluentd
google-fluentd: unrecognized service
grep: /var/log/google-fluentd/google-fluentd.log: No such file or directory

======================================================
Installation of google-fluentd complete.

Logs from this machine should be visible in the log viewer at:
  (failed to obtain logs viewer URL from agent log)

A test message has been sent to syslog to help verify proper operation.

Please consult the documentation for troubleshooting advice:
  https://cloud.google.com/logging/docs/agent

You can monitor the logging agent's logfile at:
  /var/log/google-fluentd/google-fluentd.log
======================================================

/bin/sh: 1: /etc/init.d/google-fluentd: not found
`

**Comment by qingling128** [comment]
Hi @AndryBray,

Seems the issue here is that `lsb-release` is missing from that image. Please add this line in the image's Dockerfile (might requires a custom image):

```
RUN apt-get install -y lsb-release 
```

**Comment by igorpeshansky** [comment]
Yeah, I've managed to reproduce this in the container image you referenced. Since we can't rely on the presence of lsb_release, we can adapt our script to pull in lsb-release before actually using it.

**Comment by qingling128** [comment]
Good idea. I created an internal ticket to track and prioritize it.

**Comment by igorpeshansky** [comment]
The new version of the agent installation script that fixes this issue has been released.
