### ISSUE TITLE
Support protoPayload

### ISSUE THREAD

**Issue by erlichmen** [GoogleCloudPlatform/fluent-plugin-google-cloud#2]
Currently the only metadata that is supported is severity, timestamp and message (textPayload).
It would be nice if log coming from nginx (or apache) will be send using the protoPayload which allows sending much more metadata like method, response time, path, etc.

**Comment by mr-salty** [comment]
Thanks for the feedback.  Support for structured log ingestion is definitely on our TODO list although I don't have an ETA at the moment.

**Comment by mr-salty** [comment]
#3 supports structPayload.  We don't have any plans to support protoPayload in the near term, is struct sufficient for your needs?

**Comment by erlichmen** [comment]
#3 should be enough for my needs, thanks!

**Comment by mr-salty** [comment]
struct support is now released in [google-fluentd-1.4.0](https://github.com/GoogleCloudPlatform/google-fluentd/releases/tag/v1.4.0), please give it a try and let me know if you have any feedback.
