### ISSUE TITLE
JSON detection code should be prepared to support any timestamp accepted by the timestamp computation code 

### ISSUE THREAD

**Issue by gciotta** [GoogleCloudPlatform/fluent-plugin-google-cloud#211]
There are multiple possible fields accepted by the timestamp computation code at [out_google_cloud.rb#L1440](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L1440)

The JSON detection code should be prepared to encounter any of them at [out_google_cloud.rb#L517](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L517). Currently, it only supports `time`.

In particular, under GAE Flex an [unsupported value gets inserted]( https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/blob/master/fluentd_logger/out_from_docker.rb#L33), which prevents the JSON detection code from working correctly.

See also the discussion at GoogleCloudPlatform/appengine-sidecars-docker#81

**Comment by jkohen** [comment]
@igorpeshansky can you please take a look? It seems you last investigated an issue connected with this.

**Comment by smacpher-myst** [comment]
Hi, is there any update on when we can expect this change? Thanks.

**Comment by igorpeshansky** [comment]
Closed via #333.
