### ISSUE TITLE
what jsonPayload keys are recognized by stackdriver?

### ISSUE THREAD

**Issue by jrynyt** [GoogleCloudPlatform/fluent-plugin-google-cloud#220]
What is the full list of keys that Stackdriver recognizes and displays from a jsonPayload sent by the google_cloud fluentd output?

I am using a fluentd regexp parser to extract keys from (custom) text logs, like:
```
     format /^(?<remote_addr>\S+)\s+-\s+(?<remote_user>\S+)\s+\[(?<time>.*)\]\s+"(?<method>\S+)\s+(?<uri>\S+)\s+(?<protocol>\S+)"\s+(?<status>\d+)\s+(?<bytes_sent>\d+)\s+"(?<referer>.*)"\s+"(?<user_agent>.*)"\s+"(?<x-forwarded-for>.*)".*$/
```

These keys appear in jsonPayload in Stackdriver, which is good, but the top line log display is strange: `bytes_sent`, `method`, and `user_agent` are automatically recognized and displayed in their own boxes in the SD UI, but none others (see attached). In another case, `severity` works as well. `message` does not appear on the top line, only in jsonPayload.

If possible, I would send an [HttpRequest](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#httprequest) object embedded in the log, but this doesn't seem possible with regexp.

How can I make the status and uri appear in the SD top line display, OR suppress the automatic display of the above 3 and just show the message instead? 

![screen shot 2018-04-18 at 10 56 29 am](https://user-images.githubusercontent.com/22036950/38940108-6abaedb4-42f7-11e8-8d6b-94ba8ebdde80.png)

**Comment by qingling128** [comment]
We recently published a new [doc](https://cloud.google.com/logging/docs/agent/configuration#special_fields_in_structured_payloads) that explains what fields are being extracted automatically. This should be exactly what you are looking for.

BTW, we will be adding `time` and `timestamp` fields as well. Basically:

1. If the `jsonPayload` contains a `time` field that includes `seconds` and `nanos`:
{
  "timestamp": {
    "seconds": CURRENT_SECONDS,
    "nanos": CURRENT_NANOS
  }
}
We will strip the `timestamp` from `jsonPayload` and assign it to the `LogEntry` timestamp field.

2. If the jsonPayload contains both fields below:
{
    "timestampSeconds": CURRENT_SECONDS,
    "timestampNanos": CURRENT_NANOS
}
We will strip the `timestampSeconds` and `timestampNanos` from `jsonPayload` and assign it to the `LogEntry` timestamp field.

3. If the jsonPayload contains a field `time`:
{
    "time": CURRENT_TIME
}
We will strip the `time` from `jsonPayload` and assign it to the `LogEntry` timestamp field.

**Comment by jrynyt** [comment]
I saw that doc, but it doesn't explain why bytes_sent, method, and user_agent do get recognized by SD, which then causes message to be ignored on the top-line SD display

**Comment by qingling128** [comment]
`bytes_sent`, `method` and `user_agent` are not recognized by SD. Any remaining structured record fields that are not recognized become part of jsonPayload in the [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry).

**Comment by qingling128** [comment]
Wait, I think I was talking about a different thing from what your concern is. You were asking about why things are displayed the way it is in UI. That's controlled by [Log Viewer UI](https://cloud.google.com/logging/docs/view/overview) instead of the agent.

**Comment by qingling128** [comment]
Let me try to get an answer for you.

**Comment by qingling128** [comment]
According to the Log Viewer UI team, those fields are hard coded by log templates that are different for different logs. For `Nginx`, the fields that will be recognized are:

code / status_code / size / bytes_sent / latencySeconds / response_time / method / agent / user_agent

Custom facets are also in the road map.

**Comment by jrynyt** [comment]
Thanks for getting that info. I also opened a case with GCP support and they have not been helpful.

What marks a log as being nginx? In my case, I'm just tailing a log file and using the regexp parser, so there's nothing inherently nginx-specific about it. There's a suggestion here, though https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/issues/10#issuecomment-383066167, that the tag name is significant.

**Comment by qingling128** [comment]
@jrynyt - Seems this conversation has been routed internally and there is an active conversation going on there. Asher Halpert seems to be on top of it. Custom facets is probably what you need. Please follow up with him for access to that new feature. I've also provided him the details and point of contact for the team that owns the Log Viewer UI.

**Comment by jrynyt** [comment]
Thank you @qingling128 very much for the help

**Comment by kanjieater** [comment]
Is there any public resolution on this?

**Comment by igorpeshansky** [comment]
Unless I'm missing something, this is publicly documented [here](https://cloud.google.com/logging/docs/view/overview#custom-fields).

**Comment by gutek8654** [comment]
@qingling128 will recall functionality with time and timestamp that you describe.
Have below json payload:
`{
	"traceId": "c166e839785464ca",
	"spanId": "c166e839785464ca",
	"spanExportable": "false",
	"timestampSeconds": 1654154142,
	"timestampNanos": 78000000
`
and below configuration:
`logging:
  receivers:
    journal:
      type: systemd_journald
  processors:
    parse_json:
      type: parse_json
      field: MESSAGE
  service:
    pipelines:
      pipeline:
        receivers: [journal]
        processors:
          - parse_json
`
but such log is not present in log explorer. When changing any of field (timestampSeconds or timestampNanos) by adding or removing sign log is present.
Using latest google-cloud-ops-agent 2.16
