### ISSUE TITLE
Support for on-prem Kubernetes clusters

### ISSUE THREAD

**Issue by logicfox** [GoogleCloudPlatform/fluent-plugin-google-cloud#221]
Would it be possible to leverage Stackdriver for monitoring on-prem clusters? This would help users have a unified monitoring and logging solution for all their Kubernetes installations (on-prem and cloud) and provide a way to migrate on-prem clusters to the cloud without changing the dev tooling experience.

**Comment by igorpeshansky** [comment]
Today, we don't have a sanctioned and supported solution for on-prem clusters. However, #222 will fix the one missing bit of functionality that will at least make it possible to get this working on-prem. Full on-prem support is definitely on our roadmap, but let's use this bug for the minimal feature set.
