### ISSUE TITLE
JSON parser swallowing messages

### ISSUE THREAD

**Issue by kvidhya** [GoogleCloudPlatform/fluent-plugin-google-cloud#230]
Some JSON messages are not coming through when using `format json`
Here is the json spitting from the application:

```
{"name":"db-setup","role":"dev-center-api","serviceVersion":"1.0.20","func":"db-setup","hostname":"300e017400ee","pid":1,"level":30,"type":"read","host":"eng-ide-devcenter-23cef02b4cb6.cv0su2inxpma.us-west-2.rds.amazonaws.com","msg":"Using database server { ts: '2018-07-16T16:34:00.061Z', logLevel: 'info' }","time":"2018-07-16T16:34:00.061Z","v":0}
```

Here is the fluentd config:
```
<filter us-west-2.eng.default.docker.**>
  @type parser
  <parse>
    @type multi_format
    <pattern>
      format json
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
  key_name log
  reserve_data true
</filter>
```

If there was no `parse json`, i can see my message in stack driver. But when i use `parse json` - i dont see anything come through. I can `jq` my json fine - so it is a legal json. 

Since the json parse plugin does not show me any errors, it is hard to troubleshoot when we change something in the JSON and logs start to disappear all of a sudden. Is it possible to record ParseExceptions in fluentd logs so we know about failures?

**Comment by igorpeshansky** [comment]
This is happening in the base fluentd, before the value ever gets to the output plugin. You'll need to [report this against the upstream fluentd repository](https://github.com/fluent/fluentd/issues/new).

**Comment by kvidhya** [comment]
Thanks Recreated https://github.com/fluent/fluentd/issues/2078
