### ISSUE TITLE
stackdriver output plugin swallowing JSON messages

### ISSUE THREAD

**Issue by kvidhya** [GoogleCloudPlatform/fluent-plugin-google-cloud#231]
Please Ref: 

https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/230
https://github.com/fluent/fluentd/issues/2078

In following up with the problem (https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/230) - it appears that when the message is sent out using stdout plugin, then the output is seen in the agent.log Whereas the same cannot be seen in stackdriver ... So it does seem like an issue with stackdriver plugin ..

**Comment by kvidhya** [comment]
any updates on this?

**Comment by igorpeshansky** [comment]
Looks like the fluentd issue mentioned invalid timestamps. Can you please check that the JSON entries you produce actually have valid timestamps in them? If not, the backend will reject the entries, and they'll be dropped by the plugin.

**Comment by bvandewalle** [comment]
there should be at least SOME indication somewhere that Stackdriver is rejecting it. (or in Stackdriver or in Fluentd) 
It makes debugging super complex to not have any indication that the logs weren't accepted by the backend.
