### ISSUE TITLE
File permissions too restrictive

### ISSUE THREAD

**Issue by nacholopez** [GoogleCloudPlatform/fluent-plugin-google-cloud#234]
Less restrictive permissions on files after gem installation were addressed by https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/53 but they seem back. I'm not sure about the visibility of a closed issue so I decided to open a new one:

Current state:
```
# gem install fluent-plugin-google-cloud
Successfully installed fluent-plugin-google-cloud-0.6.22

# ls -lah /var/lib/gems/2.3.0/gems/fluent-plugin-google-cloud-0.6.22/lib/fluent/plugin/
total 104K
drwxr-xr-x 2 root root 4.0K Aug  7 12:37 .
drwxr-xr-x 3 root root 4.0K Aug  7 12:37 ..
-rw-r----- 1 root root 1.7K Aug  7 12:37 monitoring.rb
-rw-r----- 1 root root  89K Aug  7 12:37 out_google_cloud.rb
```

Thanks.

**Comment by jkohen** [comment]
@yinzhi7 can you please take a look at this issue? Apparently we've solved it in the past, but it came back.

**Comment by yinzhi7** [comment]
@nacholopez 
Is this still an issue to you? I followed below. The permissions look fine. Attached below

Installing the [Stackdriver Logging agent](https://cloud.google.com/logging/docs/agent/installation#joint-install).

/opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluent-plugin-google-cloud-0.7.15/lib/fluent/plugin$ ls -lrt
total 104
-rw-r--r-- 1 root root  1024 Jul  4 10:29 statusz.rb
-rw-r--r-- 1 root root 93300 Jul  4 10:29 out_google_cloud.rb
-rw-r--r-- 1 root root  1713 Jul  4 10:29 monitoring.rb
-rw-r--r-- 1 root root  3223 Jul  4 10:29 filter_add_insert_ids.rb

**Comment by nacholopez** [comment]
Thanks @yinzhi7 for checking.

This issue seems fixed and I can no longer reproduce:
```
# gem install fluent-plugin-google-cloud
...
# ls -lah /var/lib/gems/2.3.0/gems/fluent-plugin-google-cloud-0.7.15/lib/fluent/plugin/
total 112K
drwxr-xr-x 2 root root 4.0K Aug  5 10:39 .
drwxr-xr-x 3 root root 4.0K Aug  5 10:39 ..
-rw-rw-r-- 1 root root 3.2K Aug  5 10:39 filter_add_insert_ids.rb
-rw-rw-r-- 1 root root 1.7K Aug  5 10:39 monitoring.rb
-rw-rw-r-- 1 root root  92K Aug  5 10:39 out_google_cloud.rb
-rw-rw-r-- 1 root root 1.0K Aug  5 10:39 statusz.rb
```
