### ISSUE TITLE
High CPU on service stop

### ISSUE THREAD

**Issue by talonx** [GoogleCloudPlatform/fluent-plugin-google-cloud#236]
When google-fluentd is stopped via service stop google-fluentd, it just hangs there and the command times out. The process continues to run and starts to consume high CPU (100%+) on the instance until we issue a kill -9.  A related (might be related) issue is that custom configurations in /etc/google-fluentd/config.d/ are not picked up.

Output from top (snipped a bit on the right)

```
top - 12:12:16 up 49 min,  2 users,  load average: 0.95, 1.07, 1.14
Tasks: 123 total,   2 running,  78 sleeping,   0 stopped,   0 zombie
%Cpu(s): 52.6 us,  4.8 sy,  0.3 ni, 41.6 id,  0.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 10232720 total,   152752 free,  1324752 used,  8755216 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  8585580 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                      
 4220 root      20   0  344052 106376  10780 R 109.3  1.0   1:54.33 /opt/google-fluentd/embedded/bin/ruby -Eascii-8bit:ascii-8bit /usr/sbin/google-fluentd --log /var/log/google-fluentd/google+ 
 1173 root      20   0  544716  38956  25692 S   3.3  0.4   0:24.09 /usr/share/metricbeat/bin/metricbeat -c /etc/metricbeat/metricbeat.yml -path.home /usr/share/metricbeat -path.config /etc/m+ 
 1319 root      24   4 1228904  49156   5352 S   2.0  0.5   1:05.59 /var/awslogs/bin/python /var/awslogs/bin/aws logs push --config-file /var/awslogs/etc/awslogs.conf --additional-configs-dir+ 
 1267 opentsdb  20   0 5151640 155020  22156 S   0.7  1.5   0:12.56 java -enableassertions -enablesystemassertions -DRATE_CHANGE=true -classpath /usr/share/opentsdb/lib/logback-classic-1.0.13+ 
 3335 xcollec+  20   0  236024  54020   6500 S   0.3  0.5   0:02.98 python /usr/local/xcollector/xcollector.py -t host=ade-instance -P /var/run/xcollector/xcollector.pid --daemonize            
 4215 root      20   0  171632  51120   4912 S   0.3  0.5   0:00.03 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd --log /var/log/google-fluentd/google-fluentd.log --daemon /v+ 
    1 root      20   0   38076   6268   4136 S   0.0  0.1   0:10.18 /lib/systemd/systemd --system --deserialize 25 
```

OS
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

google-fluentd --version
google-fluentd 0.14.25

I realize this is an old version, but is this is an issue which has been known to be fixed in newer ones?

**Comment by igorpeshansky** [comment]
I strongly suspect that this is fluentd attempting to flush its buffers and shut down gracefully on service stop. If it was running behind, there could be a lot of data in the buffers, hence the load.

BTW, to find the version of the package, run `gpkg -l google-fluentd` instead of `google-fluentd --version`.

**Comment by talonx** [comment]
@igorpeshansky Thanks for the pointer. It's possible that it was running behind, since I ran it on a machine with a lot of logs, and it would have started parsing them from the beginning. I'll try this on a box which does not have old logs.

**Comment by talonx** [comment]
Looks like it was due to the backlog. I emptied the logs it was tailing and it worked fine, including a restart. But this might be still an issue where we add a custom configuration while the logs it's supposed to be tailing are being written to at a high rate.

**Comment by igorpeshansky** [comment]
There's a limit to the volume of logs the agent can process (it's restricted to one core). If you go above that limit, all the agent can do is buffer and hope that the flood subsides.
There are some tuning options that might help the agent ship the data faster, but they will only help up to the above limit. Alternatively, you could shard your logs into separate processes, which would allow even higher volumes.
As it stands, this is working as intended.
