### ISSUE TITLE
Option to automatically format the LogEntry "trace" field

### ISSUE THREAD

**Issue by sebright** [GoogleCloudPlatform/fluent-plugin-google-cloud#239]
Stackdriver requires the LogEntry "trace" field to be formatted as a resource name, such as "`projects/[PROJECT-ID]/traces/[TRACE-ID]`" (https://cloud.google.com/logging/docs/agent/configuration#special_fields_in_structured_payloads).  It would be useful if fluent-plugin-google-cloud provided an option to format the trace ID read from a log entry, using the project ID detected by the plugin.

I encountered this issue while writing a demo for trace-log correlation with opencensus-java, Log4j, and Stackdriver (https://github.com/census-instrumentation/opencensus-java/pull/1382/commits/b3c8f856e266a29a49e4d2f1c4102891b4bf6b79).  The instrumented application doesn't depend on any libraries that could look up the project ID, and I wasn't sure how to format the trace ID after the application wrote it to the log file.

**Comment by igorpeshansky** [comment]
Fixed by #260.
