### ISSUE TITLE
1.x Support

### ISSUE THREAD

**Issue by andrewhowdencom** [GoogleCloudPlatform/fluent-plugin-google-cloud#251]
Hola crew; 

We're currently integrating this with various solutions, but running into trouble maintaining a backward compatible API between the various fluent versions. We're using fluent-bit as the forwarder, and had intended to use this as the aggregator -- but this depends on 0.12, which doesn't support mutual TLS super well.

Is there any track for `1.x` support?

Cheers.

**Comment by igorpeshansky** [comment]
#240.

**Comment by andrewhowdencom** [comment]
oh my god thanks! <3
