### ISSUE TITLE
Logrotate causes causes tail to stop until manual service restart

### ISSUE THREAD

**Issue by mbennett-zendesk** [GoogleCloudPlatform/fluent-plugin-google-cloud#270]
Occasionally, during logrotate on a GCE CentOS 7 VM, fluentd does not restart correctly, and logs are not tailed until the service is restarted. Using stock configuration of google-fluentd. 

Added a `sudo systemctl restart google-fluentd` to the `postrotate` block in the google-fluentd logrotate config. Still saw the same issue. Any help appreciated ASAP - this is causing Stackdriver logging to stop on the platform entirely unless it is manually checked daily.

**Comment by jkohen** [comment]
@qingling128 you've investigated logrotate issues. Could you look into this one as well?

**Comment by igorpeshansky** [comment]
This is a duplicate of GoogleCloudPlatform/google-fluentd#142.
