### ISSUE TITLE
Not extracting httpRequest.protocol and a few other fields from jsonPayload

### ISSUE THREAD

**Issue by bmenasha** [GoogleCloudPlatform/fluent-plugin-google-cloud#271]
I was looking at my app engine flexible logs and noticed that we are logging jsonPayload.httpRequest.protocol  this seems wrong as it should have been pulled out into httpRequst.protocol  (I omitted a few  unnecessary fields:: 

{
 httpRequest: {
  latency:  "0.124s"   
  referer:  "-"   
  remoteIp:  "98.229.24.149"   
  requestMethod:  "GET"   
  requestUrl:  "/test/readiness_log_check"   
  status:  200   
  userAgent:  "curl/7.60.0"   
 }
 jsonPayload: {
  appLatencySeconds:  "0.124"   
  httpRequest: {
   protocol:  "HTTP/1.1"    
  }
  latencySeconds:  "0.124"   
 }
}

We should have pulled out jsonPayload.httpRequest.protocol and made it the httpRequest.protocol structured field but didn't and think this is the fault of the fluentd plugin. 

 Looking at  fluent-plugin-google-cloud/lib/fluent/plugin/out_google_cloud.rb  we don't match this field and also miss a few others: 

There are no matches for:
    cacheFillBytes
   cacheLookup  (cacheHit)!!!
    protocol
    serverIp

We do seem to write cacheHit rather then cacheLookup but cacheHit is not even a valid httpRequest field, shouldn't that be renamed, will that cause an error on a log message contains jsonPayload.httpRequest.cacheHit?     

Thanks for investigating.

**Comment by igorpeshansky** [comment]
Is it possible to get a full initial structured log that was mis-parsed?

**Comment by salrashid123** [comment]
@qingling128 

the `serverIP` for atleast the `nginx`, and `apache2` plugin was addressed on https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/275

so we'll want to add in parts for `cache_lookup`, `cache_fill_bytes` , `protocol`

**Comment by qingling128** [comment]
This is being fixed in https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/278.
