### ISSUE TITLE
Use X-Forwarded-For  IP address value for LogEntry.httpRequest.remoteIp

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/fluent-plugin-google-cloud#276]
loadbalancers can send the `x-forwarded-for` header with the actual origin IP address and the proxies the request traversed.  

Currently, the `remoteIp` filed is populated if its present in the source logs and the fluentd agent here just reads that value.  This FR here is to alter the behavior and instead use the `x-forwarded-for` key (if present as a column in the logs at the correct position) and use the first IP provided as the true `remoteIp` value in `httpRequest`.

This requires the underlying system emittting the logs (apache,nginx,envoy) to log the header specifically and for the config to parse that out as the `x-forwarded-for` key...once thats done, the plugin here would have to look for that key and use that instead.

**Comment by igorpeshansky** [comment]
This plugin already [supports](https://cloud.google.com/logging/docs/agent/configuration#special-fields) the `httpRequest` key in the payload that will be ingested into the `LogEntry`'s `httpRequest` field. So if the underlying system is already emitting this information into the logs, the request would be to parse out the `remoteIp` and other `HttpRequest` bits while ingesting those logs via the default configs. On a raw VM, that would be in [fluentd-catch-all-config](https://github.com/GoogleCloudPlatform/fluentd-catch-all-config) (so you would have to open a feature request in that repo), but in something like GKE, that would have to be done by a sidecar container run by the user.

If the information is present in the log payload, but not nested under the `httpRequest` key, fluentd has mechanisms for transforming the payload (e.g., [record_transformer](https://docs.fluentd.org/filter/record_transformer)) that would allow one to put this in the right place. Those mechanisms would need to be enabled via the input configuration.
