### ISSUE TITLE
httpRequest.latency being dropped

### ISSUE THREAD

**Issue by thefirstofthe300** [GoogleCloudPlatform/fluent-plugin-google-cloud#280]
I am trying to get httpRequest information for nginx into Stackdriver Logging and am running into two issues. One of the issues appears to be caused by #271 and the other appears to be unreported.

I am attempting to import latency information for use in the Stackdriver Logging UI; however, it appears to be dropped, either in the fluentd-plugin-google-cloud code or by the Stackdriver API. The log looks like

```
2019-01-09 18:18:32.000000000 -0600 objectservice.fe.nginx.access: {"host":"localhost","remote_user":"-","upstream_cache_status":"-","httpRequest":{"remoteIp":"127.0.0.1","requestMethod":"GET","requestUrl":"/objectservice/healthcheck/status","responseSize":"2","status":"200","protocol":"HTTP/1.1","latency":"0.005","referer":"-","userAgent":"curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"},"severity":"INFO"}
```

after it is transformed. As you can see, there is a non-null value for latency. However, when the google-cloud plugin sends it off to Stackdriver, the latency field is completely dropped as you can see here:

![screenshot_20190109_161531](https://user-images.githubusercontent.com/3161330/50937848-6e1bac00-142a-11e9-878c-54395c08924d.png)

I have a suspicion this is API side since our GCLBs also do not have any latency related information; however, I want to start this ticket here to verify the correct information is being sent to the API.

**Comment by igorpeshansky** [comment]
According to the [documentation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest), `latency` should be

> A duration in seconds with up to nine fractional digits, terminated by 's'. Example: "3.5s".

The value you're sending doesn't have the trailing 's', so I'm guessing that's why the API drops it.

**Comment by thefirstofthe300** [comment]
You are indeed correct on this. Oversight on my part reading the docs. :man_facepalming:

I guess the one last comment I have is that latency data isn't being imported from the GCLBs. I'm not sure if this is expected but that bug appears to already be opened [elsewhere](https://issuetracker.google.com/issues/110820240).
