### ISSUE TITLE
Update to fluentd >= 1.3.0

### ISSUE THREAD

**Issue by mattysweeps** [GoogleCloudPlatform/fluent-plugin-google-cloud#282]
fluentd 1.3.0 introduces support for octet counting syslog messages:
https://www.fluentd.org/blog/fluentd-v1.3.0-has-been-released

**Comment by jkohen** [comment]
@qingling128 can you please triage? What value does this provide?

**Comment by qingling128** [comment]
This is done by https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/310.
