### ISSUE TITLE
Allow for placeholders in project_id [feature request]

### ISSUE THREAD

**Issue by sjoeboo** [GoogleCloudPlatform/fluent-plugin-google-cloud#287]
I've got a need to send logs to multiple projects, and pre-defining a set of <match>'s with all the projects is going to be far too brittle. 

I've love to be able to do, basically; 

```
<match **>
@type google-cloud
project_id ${record['logging_dest']}
....
</match>
```

But currently that doesn't seem supported (project_id is required @ plugin initialization/configure stage)?

**Comment by igorpeshansky** [comment]
Because the Stackdriver logging API requires one request per target project, this feature would potentially mean an unbounded number of requests, which would wreak havoc on the agent performance.
If you have a small number of target projects, you could achieve what you want by tagging the messages appropriately and having multiple instances of the output plugin with different configurations, e.g.:
```
<match redirect_project.**>
  @type record_reformer
  renew_record false
  remove_keys logging_dest
  tag send_to_${record['logging_dest']}.${tag_suffix[1]}
</match>
<match send_to_project1.**>
  @type google_cloud
  project_id project1
  ...
</match>
<match send_to_project2.**>
  @type google_cloud
  project_id project2
  ...
</match>
```
Would that work for you?

**Comment by sjoeboo** [comment]
@igorpeshansky 

Thats actually exactly what I'm doing currently, or, close enough (pre-defining the output project targets). Maybe if I explain my uses case it'll help:

 * We've got 100's of GCP projects with existing resources sending logs into SD for those projects. 
 * We've also got a project which houses a few multi-tenant GKE clusters.
 * We *want* to be able to re-direct logs from those GKE clusters (currently collected by the stackdriver/fluentd daemonset) to various projects so the logs live along side the associated GCP resource logs (GCE instances, etc etc). 
 * we don't want to be constantly updating the Daemonset's config with mappings, which could quickly become large. 
 * not all container logs would be redirected as such, this would strictly be an opt in for GKE tenants. 

Its 100's of projects and 100s of namespace/project mappings, and it wouldn't be static, so being able to dynamically send a given log record in the stream to a different project (using the same creds across them) would be wonderful. 

We've also raised this multi-tenant GKE cluster -> multiple destination projects use case w/ our Google  contacts

**Comment by jkohen** [comment]
@sjoeboo thanks for clarifying the use case. You did the right thing by raising this as part of multi-tenant GKE cluster with your Google contacts, as we have heard from them :-) We will prioritize our work on fluentd accordingly.

In the meantime, I'm going to close this ticket as we provided a workaround based on the current capabilities of the agent. Keep it coming!
