### ISSUE TITLE
Namespace/Namespace ID issues when shipping logs across projects?

### ISSUE THREAD

**Issue by sjoeboo** [GoogleCloudPlatform/fluent-plugin-google-cloud#288]
I'm currently running fluentd as a deamonset for my GKE cluster(s). When sending logs for a given namespace to a *different* Project than the one the GKE cluster(s) are in, StackDriver only seems to get the namespace_id populated in the filter menu, not the namespace NAME (although this information IS present in the log records). is there a way to override this to get proper namespace name population in the stackdriver interface?

**Comment by igorpeshansky** [comment]
This is working as intended. The namespace information is populated from the metadata, which is ingested against the project where the GKE cluster is running.
You may have better luck with the [new Kubernetes monitoring experience](https://cloud.google.com/monitoring/kubernetes-engine/), which uses names instead of ids in resource labels.

**Comment by sjoeboo** [comment]
I'd like to re-open this, as using a service account (homed  in another project, not the same proejct as the GKE cluster) to write logs, even logs written to the same project as the GKE cluster where the daemonset running fluentd collects logs, I'm loosing namespace_name in the Stackdriver drop-down. 

So:

GKE logs in "gke-project" -> fluentd -> "gke-project" stackdriver == namespace_name lost
GKE logs in "gke-project" -> fluentd -> $other_project(s) stackdriver == namespace_name lost

**Comment by igorpeshansky** [comment]
It's not quite clear from your explanation (I don't understand what "$other_project(s) stackdriver" refers to), but I suspect it's the same issue. For the metadata to be present, the logs must be written against the project where the resources are running, not the project where the service account lives. By default, the agent will pick up the project from the service account credentials, as that's the common case. If your service account lives in a different project, you must override the project in the agent configuration.

**Comment by sjoeboo** [comment]
Sorry, i wasn't clear, by $other_projects, i just meant, any other project i happened to be re-directing logs to. 

That all being said, i think i fixed this myself, i was using the k8s meteadata filter to pre-populate some labels/fields (https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter) which seemed to be the cause (as soon as I went back to letting the google-cloud output plugin determine everything based on the tag, the resource.label.namespace_name was correct (the name, not the id) 

Sorry for the noise!
