### ISSUE TITLE
Feature request: Preserve time key inside jsonPayload

### ISSUE THREAD

**Issue by jbuck** [GoogleCloudPlatform/fluent-plugin-google-cloud#291]
Hi there, I am using the Stackdriver Logging agent in AWS. I have a service running in a docker container that logs events with a `time` key. For example:

`{"event": "amplitudeEvent", time: "1549747084286", ...}`

The event arrives in Stackdriver Logging successfully, but it's always missing the `time` key inside `jsonPayload`. The `timestamp` key has the correct ISO8601 timestamp though. After looking at the [compute_timestamp code](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/946798d787bef1ef2e38ec8ec327bdd4ac7e4bce/lib/fluent/plugin/out_google_cloud.rb#L1621) I see that it will always delete the `time` key.

Would it be possible to add an option to preserve the `time` key inside jsonPayload?

Thanks, Jon

**Comment by qingling128** [comment]
This sounds like a feature request.

One workaround to keep a time field in the JSON:
```
<filter some_tag_to_match>
  @type record_transformer
  enable_ruby
  <record>
    time_field ${record["time"]}
  </record>
</filter>
```

This will add a `time_field` (or any other field name that is not `time`) to the JSON and it will not be removed.

Alternatively, the feature request in https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/4 should help with this use case (aka set the `time_key` to something else).

**Comment by qingling128** [comment]
Followup work would be tracked in https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/4. Closing this for now. Let us know if there is any problem applying the workaround.
