### ISSUE TITLE
unexpected interaction between tag wildcards and filenames with underscores

### ISSUE THREAD

**Issue by memory** [GoogleCloudPlatform/fluent-plugin-google-cloud#304]
We are attempting to use the k8s.gcr.io/fluentd-gcp:2.1.0 container as a sidecar to our neo4j StatefulSet pods to forward neo4j metric logs to stackdriver, and are running into inconsistent behavior generating the logName attribute of the logged events.

First, some quick background.  Neo4j is a clustered graph database that supports exporting system metrics via either direct export to graphite/prometheus, or by [writing to local csv files](https://neo4j.com/docs/operations-manual/current/monitoring/metrics/index.html).  Since there is no support for direct export of events into stackdriver, we are using the csv file approach and have configured a sidecar container in the pod running the google fork of fluentd.

The four log files we are interested in are:

```
-rw-r--r--    1 neo4j    neo4j       533978 Apr  8 17:34 /logs/metrics/vm.gc.count.g1_old_generation.csv
-rw-r--r--    1 neo4j    neo4j       540827 Apr  8 17:34 /logs/metrics/vm.gc.count.g1_young_generation.csv
-rw-r--r--    1 neo4j    neo4j       533978 Apr  8 17:34 /logs/metrics/vm.gc.time.g1_old_generation.csv
-rw-r--r--    1 neo4j    neo4j       550947 Apr  8 17:34 /logs/metrics/vm.gc.time.g1_young_generation.csv
```

The fluentd configuration (exposed to the services as a ConfigMap, as suggested at [kubernetes.io/docs](https://kubernetes.io/docs/concepts/cluster-administration/logging/#sidecar-container-with-a-logging-agent)) is:

```
<source>
  type tail
  format csv
  keys t,count,mean_rate,m1_rate,m5_rate,m15_rate,rate_unit
  time_key t
  keep_time_key true
  time_format "%s"
  types count:integer,mean_rate:float,m1_rate:float,m5_rate:float,m15_rate:float,rate_unit:string
  path /logs/metrics/vm.gc.*.csv
  pos_file /logs/metrics/vm.gc.csv.pos
  tag neo4j.vm.gc.*
  read_from_head false
</source>
```

The [fluentd documentation for the "tag" parameter](https://docs.fluentd.org/v0.12/articlesin_tail%23tag-%28required%29) says:

```
"*" can be used as a placeholder that expands to the actual file path, replacing ‘/’ with ‘.’. For example, if you have the following configuration

    path /path/to/file
    tag foo.*

in_tail emits the parsed events with the ‘foo.path.to.file’ tag.
```

So the behavior we would expect is that fluentd would parse all of those files, and forward each of them to stackdriver with a logName parameter of, e.g., neo4j.vm.gc.logs.metrics.vm.gc.count.g1_old_generation.csv

The behavior we actually see, however, is that `logName` is set to `generation.csv`, and the other elements of the filename are assigned to label elements in a way that seems deeply wrong (for starters it overrides the pod name):

```
$ gcloud logging  read logName=projects/oden-qa/logs/generation.csv --limit 1
---
insertId: vna8d5g1mwg0gu
jsonPayload:
  count: 0
  m15_rate: 0
  m1_rate: 0
  m5_rate: 0
  mean_rate: 0
  rate_unit: events/second
  t: '1554745419'
labels:
  compute.googleapis.com/resource_name: neo4j-core-0
  container.googleapis.com/namespace_name: old
  container.googleapis.com/pod_name: vm.gc.logs.metrics.vm.gc.count.g1
logName: projects/oden-qa/logs/generation.csv
receiveTimestamp: '2019-04-08T17:43:40.699914119Z'
resource:
  labels:
    cluster_name: services-1
    container_name: generation.csv
    instance_id: '8111576637290117068'
    namespace_id: old
    pod_id: vm.gc.logs.metrics.vm.gc.count.g1
    project_id: myproject
    zone: us-central1-a
  type: container
timestamp: '2019-04-08T17:43:39Z'
```

Judging by which elements of the filename are assigned to labels, I'm guessing that the underscores in the filename are what are at issue here, but I can find no documentation that suggests what the proper steps would be to prevent this.

Testing locally with the stock fluentd docker container (fluent/fluentd:v0.12-1) and a "file" output in the <match> secion and copies of the csv files from our cluster suggests that stock fluentd behaves as the documentation describes, suggesting that the problem lies with whatever changes google made with the gcp-fluentd package or on the stackdriver ingest side; stock fluentd recognizes and expands the tag correctly:

```
2019-04-08T17:46:39+00:00	neo4j.vm.gc.data.vm.gc.count.g1_young_generation.csv  {"t":"1554745599","count":0,"mean_rate":0.0,"m1_rate":0.0,"m5_rate":0.0,"m15_rate":0.0,"rate_unit":"events/second"} 
2019-04-08T17:46:40+00:00	neo4j.vm.gc.data.vm.gc.count.g1_young_generation.csv  {"t":"1554745600","count":0,"mean_rate":0.0,"m1_rate":0.0,"m5_rate":0.0,"m15_rate":0.0,"rate_unit":"events/second"}
2019-04-08T17:46:41+00:00	neo4j.vm.gc.data.vm.gc.count.g1_young_generation.csv  {"t":"1554745601","count":0,"mean_rate":0.0,"m1_rate":0.0,"m5_rate":0.0,"m15_rate":0.0,"rate_unit":"events/second"}
```

Any suggestions you could offer would be well appreciated.

**Comment by igorpeshansky** [comment]
A couple of notes:
- The image you're attempting to use is deprecated. The latest agent image is gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6 .
- This is WAI. The fluentd-gcp image is designed to be used as a DaemonSet in GKE for ingesting container logs. It is not designed to be used as a sidecar. So your use case is unsupported.
I'm glad you got it working with a hack, but we cannot really document that hack in the official docs.

**Comment by memory** [comment]
Hey Igor--

Fair enough, but https://kubernetes.io/docs/concepts/cluster-administration/logging/#sidecar-container-with-a-logging-agent explicitly points at `k8s.gcr.io/fluentd-gcp` as something that an end user should employ as a sidecar container for arbitrary apps, so at a minimum someone should update that.

Additionally, this plugin is [specifically pointed to by the fluentd documentation](https://www.fluentd.org/plugins#google-cloud-platform) as the means of publishing log events to stackdriver.  Even if I had built my own fluentd container, I (and anyone else attempting to forward logs with underscores in the name) would be having this problem.

And to be clear: I'm not necessarily asking for my hack to be documented, but the existence and behavior of the `kubernetes_tag_regexp` would have been nice to know about by some means other than groveling the source.

**Comment by igorpeshansky** [comment]
Ah, I see what's happening here. This plugin is indeed the official and supported way to ingest logs into Stackdriver. It also has special baked-in behavior that recognizes GKE deployments to support legacy use cases, which uses `kubernetes_tag_regexp` to extract the legacy `gke_container` monitored resource info. This is what you're hitting. We will take that behavior out once [Stackdriver GKE v2 support](https://cloud.google.com/monitoring/kubernetes-engine) becomes the default (so `kubernetes_tag_regexp` will actually go away). Until then, you will need to override the resource the agent uses to send the metrics by supplying a `logging.googleapis.com/local_resource_id` key in your message (currently undocumented, but can be seen [in the source](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L173) — see [the v2 configs](https://github.com/Stackdriver/kubernetes-configs/blob/master/logging-agent.yaml#L217-L220) for an example).
Apologies for the initial misunderstanding.
