### ISSUE TITLE
Inconsistency in naming of special field for trace sampling decision

### ISSUE THREAD

**Issue by sebright** [GoogleCloudPlatform/fluent-plugin-google-cloud#307]
I noticed that the special field for the trace sampling decision uses underscores ([`logging.googleapis.com/trace_sampled`](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/c90817481bb882858483822371b2c702e507cb59/lib/fluent/plugin/out_google_cloud.rb#L156)), but other special fields use camel case (e.g., `logging.googleapis.com/spanId`, `logging.googleapis.com/sourceLocation`).  I don't know if this inconsistency is an issue, though.

**Comment by qingling128** [comment]
Hmm... That is not intended. Thanks for the heads up! We'll fix it in the next major release (since it would introduce some backward incompatible change).

**Comment by igorpeshansky** [comment]
Could we not support both and deprecate the one with the underscore?

**Comment by qingling128** [comment]
@igorpeshansky - Like supporting both but having `logging.googleapis.com/traceSampled` taking precedence of `logging.googleapis.com/trace_sampled`? That sounds reasonable to me, too.

**Comment by jkohen** [comment]
@qingling128 I'm assuming the work left is to is just a cleanup. Let's make sure it gets tracked if it's necessary.

**Comment by qingling128** [comment]
Yes, this is already tracked in the major release cut change list.
