### ISSUE TITLE
Setting logName

### ISSUE THREAD

**Issue by aclowkey** [GoogleCloudPlatform/fluent-plugin-google-cloud#312]
I have a record with logName specified in the jsonPayload, but it's has:
 **"projects/<project>/logs/journald"**. 
Is this supported?

**Comment by jkohen** [comment]
@aclowkey can you give us more information? What do you expect to happen and what is happening instead?

**Comment by aclowkey** [comment]
I was expecting that having `logName` in the payload would change that logname, but it didnt'
Later I figured out that it uses the fluentd tag as the log name

**Comment by jkohen** [comment]
The relevant documentation is at:
https://cloud.google.com/logging/docs/agent/default-logs
https://cloud.google.com/logging/docs/agent/configuration#configure

I don't see a direct answer to your question. It will depend on what set of configurations you're using, which also may vary according to environment (e.g. Compute Engine vs. Kubernetes Engine).

**Comment by aclowkey** [comment]
It's pretty direct. 
The logname will be the the tag name which is passed to the output filter..

**Comment by qingling128** [comment]
Yeah, it's documented in this section: https://cloud.google.com/logging/docs/agent/configuration#default_configuration.

```
The Logging agent requires every log record to be tagged with a string-format tag; all of the filters and output plugins match a specific set of tags. The log name usually follows the format, projects/[PROJECT-ID]/logs/[TAG]. For example, this log name includes the tag structured-log:

    projects/my-sample-project-12345/logs/structured-log
```
