### ISSUE TITLE
Severity translation information -> info

### ISSUE THREAD

**Issue by wiktor2200** [GoogleCloudPlatform/fluent-plugin-google-cloud#328]
Added misc. severity translation information/info to enable getting logs from for exp. `ClickHouseDB`.

I've created pull-request which solve this issue: #327

**Comment by jkohen** [comment]
Seems connected to https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/51

**Comment by wiktor2200** [comment]
Now there is a lot of abbreviations for different severity hard coded. `Information` was missing. I solved this problem in pull-request: #327 but it needs review and approval :)
#51 is far more complicated feature :)

**Comment by wiktor2200** [comment]
Hi @igorpeshansky @jkohen! Is there any update on this one? Problem still exists for ClickhouseDB. All logs are treated as "Error" by default in GCP.

**Comment by igorpeshansky** [comment]
#327 has been merged a while ago.
