### ISSUE TITLE
Stackdriver agent use depreciated metrics in GKE

### ISSUE THREAD

**Issue by knlambert** [GoogleCloudPlatform/fluent-plugin-google-cloud#334]
I'm trying to apply[ this method ](https://kubernetes.io/docs/concepts/cluster-administration/logging/#using-a-sidecar-container-with-the-logging-agent)on a GKE private cluster running on the version 1.12.7, with Stackdriver Kubernetes Engine Monitoring enabled.

For that, I have a pod containing the fluentd agent configured this way : 

```
<source> 
  @type tail 
  path /app/logs/server.log
  pos_file /app/logs/server.log.pos
  tag app.server
  read_from_head true
  <parse>
    @type regexp
    expression ^((?<time>[^\]]*) \[(?<severity>\S*)\])*(?<message>.*)$
    time_key time
    time_format %Y-%m-%dT%H:%M:%S.%LZ
  </parse>
</source>


<match app.server>
  @type google_cloud

  k8s_cluster_name cluster-name
  k8s_cluster_location  region

  detect_json true

  <buffer>
    flush_mode interval
    retry_type exponential_backoff
    @type file
    path /var/log/google-fluentd/buffers-server
    flush_thread_count 8
    flush_interval 1s
    retry_forever false
    retry_max_times 3
    retry_max_interval 300
    chunk_limit_size 1M
  </buffer>
</match>
```

But the agent keeps pushing metrics with a depreciated format ( I'm trying to be up to date ith [this page ](https://cloud.google.com/monitoring/kubernetes-engine/migration) ).

![image](https://user-images.githubusercontent.com/16439060/62980046-70484d80-bdf3-11e9-8da5-841e5d593994.png)

It should be values like this : 

![image](https://user-images.githubusercontent.com/16439060/62980241-f95f8480-bdf3-11e9-9fd2-d53cecb0e52b.png)

Stackdriver also says I should migrate these logs, but I can't find a solution.

Thanks for your help.

**Comment by igorpeshansky** [comment]
Looks like you're trying the "sidecar container writes directly to Stackdriver" approach. While it's possible to get that to work, it's cumbersome and requires a lot of know-how into how the Stackdriver logging agent is set up.

It would be a lot easier to use the stdout approach, where your sidecar simply tails the log to its stdout, and the standard Stackdriver logging agent setup picks it up.

See https://cloud.google.com/monitoring/kubernetes-engine/installing#migrating for how to enable the new Stackdriver Kubernetes experience in an existing cluster. With the stdout approach, you should be able to find your log under the sidecar container name (e.g., if you name your sidecar `server_log`, that'll be the value of the `container_name` resource label).

Please reopen if this doesn't work for you.

**Comment by knlambert** [comment]
Hello,

Sorry I should have been more specific : 

My issue with your approach is that GKE push all the metrics into the same Stackdriver (the one in the same GKE project), and that's why I'm not using it.

This is a shared cluster. We have many teams using it, and the team 1 can't see the logs from the team 2 since it can contain sensitive informations.

The only solution we found to use stackdriver is to push the metrics into a different GCP project (dedicated to the application).
That's why I'm using this side car approach, I don't like it either, but I'm out of solutions here :(

**Comment by igorpeshansky** [comment]
Yes, logging from shared clusters is a known feature request. Unfortunately, I don't have any timelines to share at the moment. As of today, your use case is unsupported. You may get it working, but we won't be able to help you if it breaks.

Your best bet for getting this working would be to copy the full fluentd configuration from the new Stackdriver setup. You'll want all the filters, transformers, and output (match) clauses — basically, everything but the inputs (sources). A sidecar per log producer container will be very inefficient, but it should work.

As for making it a bit more efficient, are your teams running their workloads in separate namespaces? If so, you could set up one fluentd DaemonSet per namespace, with its own workload identity, and point it at the log files from that namespace. If the teams are fixed, you may even be able to set up a single fluentd DaemonSet with multiple output (match) clauses, each with its own project id, matching each team's namespace, but that would require a single identity to be able to write logs to all of the projects.
