### ISSUE TITLE
Support sending logs from other Cloud to Stackdriver?

### ISSUE THREAD

**Issue by emillg** [GoogleCloudPlatform/fluent-plugin-google-cloud#348]
Can I use this plugin to send logs from non-GCP/AWS cloud to Stackdriver? If yes, any documentation?

Thanks!

**Comment by igorpeshansky** [comment]
Yes, we do currently support sending logs from AWS EC2 VMs, but only via the `google-,fluentd` package, see https://cloud.google.com/logging/docs/agent/#environments. Please file feedback on the documentation if you find something lacking.

**Comment by emillg** [comment]
Hi,

I was wondering if I can send logs from IBM Cloud to Stackdriver? Thanks

**Comment by igorpeshansky** [comment]
Oh. Apologies, I missed the `/` in your original question.

No, this plugin currently does not support sending logs from other clouds. We are partnering with a company called "Blue Medora", who allow sending logs into Stackdriver from environments that aren't natively supported. Please see if their [BindPlane product](https://bluemedora.com/products/bindplane/) addresses your needs.

**Comment by emillg** [comment]
@igorpeshansky Thanks for the info!
