### ISSUE TITLE
Add support for dynamically setting log_name from record

### ISSUE THREAD

**Issue by voidpirate** [GoogleCloudPlatform/fluent-plugin-google-cloud#350]
When running on GKE the logName is always set to the tag (by default stdout/stderr), thus making it difficult to customize the logName dynamically per application or even different logNames within a single application.

The fluentd DaemonSet installation used: https://github.com/GoogleCloudPlatform/kubernetes-engine-customize-fluentd/tree/master/kubernetes.

I see two possible ways to dynamically set the logName.

1.) Add config option `log_name` ([todo already in code](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L462)), and if set would use the record['logName'] to set the logName when uploading to Stackdriver. The value should automatically be formatted to the [logName LogEntry spec](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#FIELDS.log_name). If the config option is not set, or if the logName is not part of the record, it should fallback to the current way of using the tag.

2.) Using [record_reformer](https://github.com/sonots/fluent-plugin-record-reformer) plugin? It seems possible, but have not been successful. Any tips here would be helpful.

This feature would be nice to get correlated logs by HTTP request for applications on GKE. More information about correlating log entries can be found [here](https://medium.com/google-cloud/combining-correlated-log-lines-in-google-stackdriver-dd23284aeb29).

**Comment by voidpirate** [comment]
We are currently in the process of migrating services from GAE to GKE. GAE Stackdriver log viewer is grouping the log entries from the same HTTP request together under a single drop down, see image below for context taken from [this blog](https://medium.com/google-cloud/combining-correlated-log-lines-in-google-stackdriver-dd23284aeb29), as I'm unable to share our exact logs. 
![image](https://user-images.githubusercontent.com/1903318/68310156-5fab1a80-0064-11ea-83aa-dd7001e64710.png)

We do not want to lose this functionality when running services on GKE.

In my tests I'm able to update the log event tag within the `record_reformer` block ([setting this to static value](https://github.com/GoogleCloudPlatform/kubernetes-engine-customize-fluentd/blob/master/kubernetes/fluentd-configmap.yaml#L138) and updating any other filter/match blocks looking for `stderr,stdout`) to something other than `stderr,stdout` and the log name within Stackdriver log viewer shows correctly, although the log name is static and not so helpful.

**Comment by igorpeshansky** [comment]
Ah, so this is about grouping by HTTP request... Have you seen https://cloud.google.com/logging/docs/structured-logging#apache-config and https://cloud.google.com/appengine/docs/flexible/dotnet/writing-application-logs#related-app-logs? You can store the trace id in the logs via a [special payload field](https://cloud.google.com/logging/docs/agent/configuration#special-fields).
