### ISSUE TITLE
Fluentd log full with ERROR after upgrading to GKE 1.16

### ISSUE THREAD

**Issue by lechen26** [GoogleCloudPlatform/fluent-plugin-google-cloud#407]
Hi

after GKE 1.16 upgrade, i've started to see 2 things:
- the log is full with the following message:
`Unable to export to Monitoring service because: GaxError RPC failed, caused by 3:One or more TimeSeries could not be written: Unrecognized resource type: container.: timeSeries[0]`

any idea?
thanks

**Comment by igorpeshansky** [comment]
Hi. Known issue. The fix is being rolled out, and will be available in version 1.16.9-gke.6.
