### ISSUE TITLE
Pinning of specific FluentD version

### ISSUE THREAD

**Issue by smstone** [GoogleCloudPlatform/fluent-plugin-google-cloud#413]
Hello,

We would like to run the current latest version of FluentD (1.11.1) with this plugin, however a strict version dependency is declared here within your plugin here: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/bda422b8654f1597d5cb602d8a8bb5db844913f9/fluent-plugin-google-cloud.gemspec#L22

This causes FluentD to be downgraded to version to 1.7.4 when we install this plugin with bundler. I am wondering if it possible to instead use something like `spec.add_dependency "fluentd", ">= 1.7.4", "< 2"` instead of the explicit version?

Thanks for your time,
Steven

**Comment by igorpeshansky** [comment]
This plugin is designed specifically for use with the `google-fluentd` package, which bundles fluentd 1.7.4. We do not test the plugin with fluentd versions later than 1.7.4, and can't guarantee that it would work. I'll let @qingling128 make the decision on whether (and how) we want to support that use case.

Can you please expand on what features you're looking for in fluentd 1.11.1 that aren't present in 1.7.4? Thanks.

**Comment by smstone** [comment]
Thanks for the response. I was unaware this is specifically for use with the `google-fluentd` gem, so that makes more sense.

We are not looking at any specific features, however it was more for the bug fixes and enhancements available, as 1.7.4 is getting close to being a year old.

**Comment by igorpeshansky** [comment]
Note: `google-fluentd` is a Linux package, not a gem. We do periodically upgrade the `fluentd` gem in that package. Maybe it's time to bump it again, but, as I said, I'll let @qingling128 make that decision.

**Comment by qingling128** [comment]
I happened to start the work to ugprade Fluentd to 1.11 yesterday for some other reason. The upgrade will need to pass all our validations. Stay tuned. We will provide an ETA once the initial result comes out.

**Comment by jkschulz** [comment]
Hey Steven,

I just finished initial testing for the upgrade to fluentd v1.11.2 and it passed! 
Sent out:
- PR for the plugin: #418 
- PR for google-fluentd: GoogleCloudPlatform/google-fluentd#283

Once those are submitted, it should be 4-7 days before they make it out into a release.

**Comment by jkschulz** [comment]
More specifically, the fluentd update will be released in `google-fluentd` 1.8.0 + `fluent-plugin-google-cloud` 0.10.0

**Comment by jkschulz** [comment]
[1.8.0 was released on Aug 17](https://github.com/GoogleCloudPlatform/google-fluentd/releases/tag/1.8.0).
