### ISSUE TITLE
Why is google-fluentd starting with the --no-supervisor option?

### ISSUE THREAD

**Issue by bvandewalle** [GoogleCloudPlatform/fluent-plugin-google-cloud#424]
After discovering a bottleneck cause by google-fluentd not treating logs fast enough (and therefore blocking a docker container which was outputting the log), I'm trying to make it "multi worker".

However, google-fluentd hardcoded the `--no-supervisor` option as part of the systemd startup script. I'm not sure why, but it prevents fluentd to load with multiple workers.

Is there a reason behind it? Can you remove this parameter so that the amount of workers will be decided based on the config file?

**Comment by igorpeshansky** [comment]
This was done in an attempt to save memory. See the discussion in GoogleCloudPlatform/google-fluentd#225.

**Comment by bvandewalle** [comment]
I thought you now supported multiple workers? (based on https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/296 )

Or at least make it an option somewhere?

**Comment by bvandewalle** [comment]
Any news on this?

**Comment by qingling128** [comment]
Looks like this was fixed by https://github.com/GoogleCloudPlatform/google-fluentd/pull/298.
