### ISSUE TITLE
Plugin does not set severity level based on stream type

### ISSUE THREAD

**Issue by vlad-dragos** [GoogleCloudPlatform/fluent-plugin-google-cloud#43]
Hello,

I'm using a container to send the logs from a Kubernets pod to Google Cloud Logging and I've noticed that all the log entries have no severity level. From what I understand the plugin should set a severity level based on the "stream" field: ERROR for stderr and INFO for stdout.

**Comment by mr-salty** [comment]
I believe that change has not made it into a google-fluentd release yet, but it should be coming soon.

If you're able to update the cloud logging gem in the logging container, that should work: /usr/sbin/google-fluentd-gem update fluent-plugin-google-cloud

**Comment by mr-salty** [comment]
@vlad-dragos can you confirm this is fixed in google-fluentd 1.5.4 or gem 0.4.10

**Comment by sadovnychyi** [comment]
Is it possible to capture severity information using regexp like `format /^(?<message>(?<time>[^ ]*\s*[^ ]* [^ ]*) .*)$/` in config file?

That sample is used to capture timestamp from syslogs, but does not seems to work properly. WOuld like to see documentation about this.

**Comment by mr-salty** [comment]
@sadovnychyi I opened #51 to track the documentation issue, I'll follow up there, since the original issue here was about the special-purpose support for setting severity in k8s (which I believe is fixed)

**Comment by igorpeshansky** [comment]
This should be fixed by #76. Will close once the gem is released.

**Comment by a-robinson** [comment]
I think this can be closed now
