### ISSUE TITLE
calling URI.open via Kernel#open is deprecated

### ISSUE THREAD

**Issue by moxli** [GoogleCloudPlatform/fluent-plugin-google-cloud#431]
I am using the latest version of this plugin and receive the following two log messages (LogLevel Error) on startup.

My environment:
- Debian 10
- td-agent 4
- fluent-plugin-google-cloud 0.10.2

I installed the plugin like this:
/usr/sbin/td-agent-gem install --no-document fluent-plugin-google-cloud -v ${fluent_plugin_gcloud_version}

`/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-google-cloud-0.10.2/lib/fluent/plugin/common.rb:114: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open`
`/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-google-cloud-0.10.2/lib/fluent/plugin/common.rb:136: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open`

**Comment by igorpeshansky** [comment]
Fixed via #500.
