### ISSUE TITLE
Support protoPayload

### ISSUE THREAD

**Issue by iwasa-kosui** [GoogleCloudPlatform/fluent-plugin-google-cloud#434]
In Google Cloud Logging, there are textPayload, jsonPayload, and protoPayload in payload types.
However, the plugin only supports textPayload and jsonPayload.

https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L1719-L1751

With type `type.googleapis.com/google.appengine.logging.v1.RequestLog`, protoPayload is very useful because it can group per a request. It must be required who use Google Cloud Logging not with GAE, but GKE, On-Premise, and the other clouds...

**Comment by sophieyfang** [comment]
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry
I feel like not a lot of services support protoPayload..

**Comment by iwasa-kosui** [comment]
Thank you.

Yes. Only GAE supports it officially. However, we implement a logger using protoPayload in our application.
I want group logs per a request as the below.

![](https://miro.medium.com/max/1400/1*1VL397D19bPdKZ1jfqZ1uQ.png)

If I use `textPayload` and `jsonPayload`, I have to use `trace` to group logs per a request. Moreover, we have to prepare child log and parent log to do this. Moreover, in using trace, we can't group between the other resource.

However, with protoPayload, there is no need to concern the constraints. All we need is to put logs into `protoPayload.line` to do this.

**Comment by igorpeshansky** [comment]
Ingestion using `protoPayload` is not supported by the API — that field is output-only. The GAE infrastructure uses different (internal) ingestion methods.

You should be able to group by request by [adding the httpRequest special field to the JSON payload](https://cloud.google.com/logging/docs/agent/configuration#special-fields).

**Comment by iwasa-kosui** [comment]
> You should be able to group by request by adding the httpRequest special field to the JSON payload.

Yes. However, as I said, have to use trace to group logs per a request with using this.

> Ingestion using protoPayload is not supported by the API

I tried using protoPayload with the API, and it was succeeded. Ok, I will make PR.

**Comment by iwasa-kosui** [comment]
> You should be able to group by request by adding the httpRequest special field to the JSON payload.

Yes. However, as I said, have to use trace to group logs per a request with using this.
In addition, JSON payload way is not elegant because it's a bother to investigate the specific request.
The below is procedure to do this. It takes too much time.

1. Search in the parent logName with user-agent and time.
1. Confirm the request you found and remind trace id in it.
1. Search in the child logName with the trace id.
1. You can get all logs for the request.

> Ingestion using protoPayload is not supported by the API

Of course not. It is read-only in oficially.
Meanwhile, we can write log with protoPayload with the API. I tried using protoPayload with it, and it was succeeded.
You can use protoPaylod with both of REST API and gRPC `API.```

**Comment by igorpeshansky** [comment]
Only two proto types are accepted by the API in `protoPayload`: `type.googleapis.com/google.cloud.audit.AuditLog` and `type.googleapis.com/google.appengine.logging.v1.RequestLog`. The API team tells us that no clients should be using `protoPayload` anymore, so we won't be able to implement this request.

You don't need `protoPayload` to get request correlation, see, e.g., [this Medium post](https://medium.com/google-cloud/combining-correlated-log-lines-in-google-stackdriver-dd23284aeb29). If you feel there's functionality you can only achieve via `protoPayload` and not via `jsonPayload`, please provide some examples, and we'll help you find a way to do the same via `jsonPayload`.
