### ISSUE TITLE
Version conflict with fluent-plugin-elasticsearch

### ISSUE THREAD

**Issue by max0ne** [GoogleCloudPlatform/fluent-plugin-google-cloud#442]
Hi,
I'd like to use `fluent-plugin-google-cloud` together with `fluent-plugin-elasticsearch`, however I'm running into a version conflict between:
* `fluent-plugin-google-cloud@0.10.4` > `googleauth = 0.9.0` > ` faraday ~> 0.12`
* `fluent-plugin-elasticsearch@4.2.1` > `elasticsearch@7.10.0` > `elasticsearch-transport = 7.10.0` > ` faraday ~> 1`

The solution here should be update dependency of `googleauth` one of the later versions, any versions later than `0.11.0` uses ` faraday >= 0.17.3, < 2.0` which should work with elasticsearch plugin.

I can make a PR to fix this, but want to make sure if there's any cadence to version updates, anything I need to watch out for?

**Comment by igorpeshansky** [comment]
This should work after #504.
