### ISSUE TITLE
Specifying credentials path

### ISSUE THREAD

**Issue by anishk25** [GoogleCloudPlatform/fluent-plugin-google-cloud#446]
Does the plugin support specifying the credentials path to use for logging to google cloud? The documentation says that the plugin uses the default credentials.  I was going through the source code and I do see there is a `private_key_path` param but its marked as deprecated. 

Here is where I found the path parameter: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/32510c2f277eb1d988e57e7631dfef846661299d/lib/fluent/plugin/filter_analyze_config.rb#L107

**Comment by igorpeshansky** [comment]
The path parameter is actually defined [here](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L353), and you're right, it is deprecated. The plugin uses the `googleauth` library, which will look for the credentials in the known location (`/etc/google/auth/application_default_credentials.json`) or the file path specified by the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, as documented [here](https://cloud.google.com/logging/docs/agent/authorization#copy-private-key). Hope this helps.

**Comment by anishk25** [comment]
Thanks
