### ISSUE TITLE
Common labels are modified and populated across iterations when looping over tags

### ISSUE THREAD

**Issue by swalkowski** [GoogleCloudPlatform/fluent-plugin-google-cloud#50]
In each iteration, write_log_entries_request['commonLabels'] are set to @common_labels:

https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/83e66bc4f1d277a66d06d6e31133f0bc9ea4da33/lib/fluent/plugin/out_google_cloud.rb#L313

However, setting values inside write_log_entries_request['commonLabels'] results in modifying the original @common_labels, so write_log_entries_request['commonLabels'] in the next iteration are initialized with common labels from the previous iteration.

This behavior is somewhat misleading because if a label is not set in the next iteration, it carries a value from the previous iteration, while it shouldn't be included at all. It looks like this issue affects only the Cloud Functions service for now but it would be good to resolve it in a generic way so that future modifications do not hit the same problem.

**Comment by mr-salty** [comment]
Fixed by #59
