### ISSUE TITLE
File permission in released gem is too strict

### ISSUE THREAD

**Issue by trekdemo** [GoogleCloudPlatform/fluent-plugin-google-cloud#53]
In the latest version of the gem the `lib/fluent/plugin/out_google_cloud.rb` file has a permission of `640` which can be problematic in case the gem was installed by `root`. 

Is it possible to re-release it with fixed permission?

**Comment by mr-salty** [comment]
I released 0.4.14 with the plugin mode set to 0644.

I'm a bit surprised there's not a way to specify this in the gemspec rather than using the permissions on my filesystem, so I'll have to devise a way to ensure it doesn't happen again in the future.   See also https://github.com/rubygems/rubygems/pull/1041

**Comment by trekdemo** [comment]
@mr-salty thank you very much. Keep up, you're all awesome! :+1:

**Comment by ndhoule** [comment]
@mr-salty I have 0.4.16 installed and I'm seeing this issue on `out_google_cloud.rb`, `test_out_google_cloud.rb`, and `fluent-plugin-google-cloud.gemspec`.

**Comment by mr-salty** [comment]
Argh - sorry, I didn't follow up on my "devise a way to ensure it doesn't happen again" when I closed the issue, and it did happen again.  I will push a fixed 0.4.17.

**Comment by mr-salty** [comment]
I pushed 0.4.17 which is identical to 0.4.16 but with fixed permissions.  Sorry for the trouble.

It looks like https://github.com/rubygems/rubygems/pull/1041 will fix this but it hasn't been merged.  My umask is 027 which is what leads to the issue.  I'll leave this open to investigate an interim solution.  AFAIK I can't run arbitrary code (to check the permissions) in the gemspec which would be ideal but maybe I can at least add something to the Rakefile so it will fail when I run pre-release tests.

**Comment by ndhoule** [comment]
Thanks for the prompt fix!

**Comment by nacholopez** [comment]
Is this issue back?

Version 0.4.17
```
# gem install fluent-plugin-google-cloud -v 0.4.17
Successfully installed fluent-plugin-google-cloud-0.4.17
1 gem installed
# ls -lah /var/lib/gems/2.3.0/gems/fluent-plugin-google-cloud-0.4.17/lib/fluent/plugin/out_google_cloud.rb
-rw-r--r-- 1 root root 33K Jul 20 09:30 /var/lib/gems/2.3.0/gems/fluent-plugin-google-cloud-0.4.17/lib/fluent/plugin/out_google_cloud.rb
```

Latest release: 0.6.21
```
# gem install fluent-plugin-google-cloud
Successfully installed fluent-plugin-google-cloud-0.6.21
1 gem installed
# ls -lah /var/lib/gems/2.3.0/gems/fluent-plugin-google-cloud-0.6.21/lib/fluent/plugin/out_google_cloud.rb
-rw-r----- 1 root root 89K Jul 20 09:34 /var/lib/gems/2.3.0/gems/fluent-plugin-google-cloud-0.6.21/lib/fluent/plugin/out_google_cloud.rb
```

Thanks
