### ISSUE TITLE
gem dependency breaks plugin install

### ISSUE THREAD

**Issue by nshttpd** [GoogleCloudPlatform/fluent-plugin-google-cloud#54]
Looks like on Jan 14th the 0.9 version of the google-api-client was published. The current gemspec has 

```gem.add_runtime_dependency 'google-api-client', '>= 0.8.6', '<= 0.9'```

so 0.9 gets picked up and installed, but it looks like with this version release you need to pick and choose what parts of the API to use instead of everything being there. That should probably be changed to '< 0.9' in the dependency requirement.

**Comment by mr-salty** [comment]
indeed I intended that to be < 0.9 to prevent this very issue but I committed the wrong thing.

**Comment by nshttpd** [comment]
I've done something similar in the past. Only other thing I ran into was out_google_cloud.rb was installed chmod 0640. Since td-agent doesn't run as root it couldn't open it when configured to write to GCL. A simple ansible file chmod fix took care of that.

**Comment by mr-salty** [comment]
I also pushed this to rubygems as 0.4.14 - I tested it myself and it looks good but please let me know if you have any issues.
