### ISSUE TITLE
Logs are dropped if project id contains colon

### ISSUE THREAD

**Issue by herohde** [GoogleCloudPlatform/fluent-plugin-google-cloud#66]
For a project "foo.com:bar" configured with the latest version of the plugin, I now see a stream of:

`[warn]: Dropping 2 log message(s) error_class="Google::Apis::ClientError" error="notFound: Project does not exist: foo.com%3Abar"`

in the fluentd logs. It previously worked and the same configuration with a project id without colon works as well. It seems like the google-api-client upgrade to 0.9 causes project id with colon to be escaped incorrectly somewhere, likely the URI encoding.

Is this a known issue with the v1beta3 logging api, btw? I see v2beta1 has a different schema for writing logs, notably not including the project in the URI.

**Comment by mr-salty** [comment]
Sounds like this was an issue with the cloud logging backend and not the plugin, so I'll close this.
