### ISSUE TITLE
Switch to a more performant JSON parsing library

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/fluent-plugin-google-cloud#67]
We do a bunch of JSON parsing, and Ruby's JSON parsing isn't cheap. We should consider switching to a more performant parser, as Fluentd recently did (https://github.com/fluent/fluentd/pull/748).

@mr-salty @bokowski

**Comment by jkohen** [comment]
Let's reopen if necessary to meet performance goals.
