### ISSUE TITLE
Structured logging for Amazon Elastic Container Service

### ISSUE THREAD

**Issue by cgst** [GoogleCloudPlatform/fluent-plugin-google-cloud#72]
fluent-plugin-google-cloud does not attempt to parse container log message as JSON when running on Amazon ECS. Because of that, log messages created in ECS containers get sent to GCP as:

"metadata": { ... },
"structPayload": {
    "log": "{\"key\": \"value\"}"
}

Is there a way to tell fluent-plugin-google-cloud to parse the "log" record value as JSON on AWS?

**Comment by cgst** [comment]
I've ended up using https://github.com/tagomoris/fluent-plugin-parser. For anyone running into this issue, here's one possible solution:

```
<source>
  @type forward
</source>

<filter **>
  @type parser
  format json
  key_name log
  hash_value_field parsed
  reserve_data yes
  suppress_parse_error_log yes
  ignore_key_not_exist yes
</filter>

<match **>
  # Your regular fluent-plugin-google-cloud config goes here...
  type google_cloud
</match>
```

You'll need to install the `parser` fluent plugin:

`$ /opt/google-fluentd/usr/sbin/google-fluentd-gem install fluent-plugin-parser`

**Comment by vially** [comment]
I suppose you're not able to change the container, right? Because if you are, you might be able to fix it from inside the container.

Unless I've misunderstood your problem, your container right now outputs something like:

```
...
{"log": "{\"key\": \"foo\"}"}
{"log": "{\"key\": \"bar\"}"}
...
```

Why not change it to output JSON objects directly:

```
...
{"log": {"key": "foo"}}
{"log": {"key": "bar"}}
...
```

**Comment by jkohen** [comment]
Thanks for of you for suggestion a solution. I'm glad it got worked out.
