### ISSUE TITLE
Entire log batch is dropped when 1 entry is too large

### ISSUE THREAD

**Issue by smmckay** [GoogleCloudPlatform/fluent-plugin-google-cloud#79]
`2016-08-17 20:01:40 +0000 [warn]: Dropping 48 log message(s) error_class="Google::Apis::ClientError" error="badRequest: Log entry with size 189059 bytes exceeds maximum size of 112640 bytes"`

There's no way that over-large entry is going be submitted, but it sucks to lose the other 47 entries.

**Comment by munangst** [comment]
After the plugin migrates to the v2 logging API, it will be possible to use the [partialSuccess flag](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/write#request-body) to have only the invalid entries rejected. @igorpeshansky

**Comment by qingling128** [comment]
This can be achieved by setting `partial_success true`. See doc at https://cloud.google.com/logging/docs/agent/configuration#cloud-fluentd-config.
