### ISSUE TITLE
Fluentd LogEntry JSON parsing problem

### ISSUE THREAD

**Issue by nyilmaz** [GoogleCloudPlatform/fluent-plugin-google-cloud#88]
Hi there,

I have my logs written to stdout with [LogEntry](https://cloud.google.com/logging/docs/api/reference/rest/Shared.Types/LogEntry) as JSON. Therefore my log is like;

```
{  
   "labels":{  
      "label1":"label-value-1"
   },
   "logName":"projects/xxx-experimental/logs/xxx.yyyy.zzzz.DataSourcesAutoConfiguration",
   "resource":{  
      "labels":{  
         "project_id":"xxx-experimental"
      },
      "type":"global"
   },
   "severity":"INFO",
   "textPayload":"DS has been registered",
   "timestamp":"2016-10-20T12:32:00.077Z"
}
```

However in Google cloud console this log entry is shown below `structPayload`. Is that a normal behaviour? I expect merging the metadata provided by fluentd and my logEntry object in cloud console. Apparently it is not. LogEntry is just appended as a subtree of `structPayload`.

**Comment by jkohen** [comment]
@nyilmaz can you show what you see and what you'd expect to see? I'm not sure I understand the issue.

**Comment by jkohen** [comment]
Given that this is an old issue and I haven't heard back from you in two weeks, I'm going to close it. Feel free to reopen it in the future if you still need it.

**Comment by igorpeshansky** [comment]
This is not how JSON detection works. For a list of special fields recognized by the agent and how they are propagated into the resulting log entry, see https://cloud.google.com/logging/docs/agent/configuration#process-payload.

**Comment by jkohen** [comment]
@nyilmaz please let me know if @igorpeshansky 's suggestion helped. If you still need assistance with this issue, please reopen it.
