### ISSUE TITLE
Hanging fluentd

### ISSUE THREAD

**Issue by crassirostris** [GoogleCloudPlatform/fluent-plugin-google-cloud#98]
Recently we encountered a hanging fluentd problem in GKE cluster. Kubernetes [logging agent](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-gcp/fluentd-gcp-image) is periodically stops sending any logs and writing anything to it's own logs until the manual restart is invoked.

After some research we found [this thread](https://groups.google.com/forum/#!topic/fluentd/H3Ilx38hFl0). In short, http connection without a timeout was hanging.

From the quick peek to the [code](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb) I couldn't find any timeout setup for the client. May this be a problem or is timeout set up somewhere deeper in the library code?

**Comment by igorpeshansky** [comment]
@crassirostris Wasn't this the issue we debugged together? As I recall, there was a networking problem with the container. Can you still reproduce this?

**Comment by crassirostris** [comment]
@igorpeshansky No, that's different. It happens randomly and we couldn't reproduce it on purpose. It still happens sometimes, but now that we have liveness probe, it's not a big issue any more

**Comment by igorpeshansky** [comment]
Any pointers on how to debug this? Can we catch it in the act and at least capture the logs?

**Comment by crassirostris** [comment]
@igorpeshansky Nothing in the logs, when this happens, fluentd just hungs

Not much of the information, I understand. Let's close this until we encounter this problem again and can take a memory dump

**Comment by igorpeshansky** [comment]
@crassirostris Sounds good, thanks. Please reopen when we have more data to go on.
